; generated by generate_custom_xz_geometry.py
; Custom XZ-plane geometry with optional tangential B-pull based on calibration tip-angle polynomial
; C-only moves use c_feed; XYZ/B moves use motion/print feed
; Axes: X=X Y=Y Z=Z B=B C=C U=U
; Calibration B range: [-5.200, 0.000]
; C(180) command from calibration: 180.000
; Feeds: motion=300.0, print=300.0, C-only=5000.0
; Extrusion disabled (set --extrusion-per-mm > 0 to emit U-axis commands)
; NOTE: Step 4 prompt had contradictory C setting; default bottom-half tangential C uses 180 (configurable)
G90
; === STEP 1: Figure 1 on first XZ plane (Y=start_y), non-tangential, B=0, C=0 ===
G1 C0.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; move to step1 start
; BEGIN LINE: STEP1 Figure1 angle=0 deg
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 a=0
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=0 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=0 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=0 wp3
; BEGIN LINE: STEP1 Figure1 angle=5 deg
G1 X72.454 Y40.000 Z-106.815 B0.000 C0.000 F300 ; fig1 +5
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -5
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=5 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=5 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=5 wp3
; BEGIN LINE: STEP1 Figure1 angle=10 deg
G1 X72.454 Y40.000 Z-103.262 B0.000 C0.000 F300 ; fig1 +10
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -10
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=10 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=10 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=10 wp3
; BEGIN LINE: STEP1 Figure1 angle=15 deg
G1 X72.454 Y40.000 Z-99.597 B0.000 C0.000 F300 ; fig1 +15
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -15
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=15 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=15 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=15 wp3
; BEGIN LINE: STEP1 Figure1 angle=20 deg
G1 X72.454 Y40.000 Z-95.756 B0.000 C0.000 F300 ; fig1 +20
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -20
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=20 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=20 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=20 wp3
; BEGIN LINE: STEP1 Figure1 angle=25 deg
G1 X72.454 Y40.000 Z-91.662 B0.000 C0.000 F300 ; fig1 +25
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -25
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=25 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=25 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=25 wp3
; BEGIN LINE: STEP1 Figure1 angle=30 deg
G1 X72.454 Y40.000 Z-87.221 B0.000 C0.000 F300 ; fig1 +30
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -30
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=30 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=30 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=30 wp3
; BEGIN LINE: STEP1 Figure1 angle=35 deg
G1 X72.454 Y40.000 Z-82.306 B0.000 C0.000 F300 ; fig1 +35
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -35
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=35 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=35 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=35 wp3
; BEGIN LINE: STEP1 Figure1 angle=40 deg
G1 X72.454 Y40.000 Z-76.751 B0.000 C0.000 F300 ; fig1 +40
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -40
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=40 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=40 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=40 wp3
; BEGIN LINE: STEP1 Figure1 angle=45 deg
G1 X72.454 Y40.000 Z-70.315 B0.000 C0.000 F300 ; fig1 +45
G1 X112.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; fig1 -45
; END LINE
G1 X112.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=45 wp1
G1 X32.454 Y40.000 Z-60.315 B0.000 C0.000 F300 ; STEP1 return angle=45 wp2
G1 X32.454 Y40.000 Z-110.315 B0.000 C0.000 F300 ; STEP1 return angle=45 wp3
; === STEP 2: Figure 1 on second XZ plane (Y=start_y+20), tangential, C=180 ===
G1 C180.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X7.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; move to step2 start (Y+20 plane)
G1 X7.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP2 line 0 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=0 deg
G1 X87.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; fig1_tan a=0 (poly=0.0)
; END LINE
G1 X87.546 Y60.000 Z-60.315 B0.000 C180.000 F300 ; STEP2 return angle=0 wp1
G1 X7.546 Y60.000 Z-60.315 B0.000 C180.000 F300 ; STEP2 return angle=0 wp2
G1 X7.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP2 return angle=0 wp3
G1 X7.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP2 line 5 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=5 deg
G1 X47.546 Y60.000 Z-106.815 B0.000 C180.000 F300 ; fig1_tan +5 (poly=5.0)
G1 X58.583 Y60.000 Z-114.450 B-2.726 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -5 (poly=95.0))
G1 X98.583 Y60.000 Z-117.950 B-2.726 C180.000 F300 ; fig1_tan -5 (poly=95.0)
; END LINE
G1 X88.758 Y60.000 Z-60.004 B-0.228 C180.000 F300 ; STEP2 return angle=5 wp1
G1 X8.758 Y60.000 Z-60.004 B-0.228 C180.000 F300 ; STEP2 return angle=5 wp2
G1 X8.758 Y60.000 Z-110.004 B-0.228 C180.000 F300 ; STEP2 return angle=5 wp3
G1 X8.758 Y60.000 Z-110.004 B-0.228 C180.000 F300 ; STEP2 line 10 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=10 deg
G1 X48.758 Y60.000 Z-102.951 B-0.228 C180.000 F300 ; fig1_tan +10 (poly=10.0)
G1 X58.803 Y60.000 Z-111.571 B-2.850 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -10 (poly=100.0))
G1 X98.803 Y60.000 Z-118.624 B-2.850 C180.000 F300 ; fig1_tan -10 (poly=100.0)
; END LINE
G1 X89.885 Y60.000 Z-59.932 B-0.445 C180.000 F300 ; STEP2 return angle=10 wp1
G1 X9.885 Y60.000 Z-59.932 B-0.445 C180.000 F300 ; STEP2 return angle=10 wp2
G1 X9.885 Y60.000 Z-109.932 B-0.445 C180.000 F300 ; STEP2 return angle=10 wp3
G1 X9.885 Y60.000 Z-109.932 B-0.445 C180.000 F300 ; STEP2 line 15 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=15 deg
G1 X49.885 Y60.000 Z-99.214 B-0.445 C180.000 F300 ; fig1_tan +15 (poly=15.0)
G1 X58.989 Y60.000 Z-108.584 B-2.974 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -15 (poly=105.0))
G1 X98.989 Y60.000 Z-119.302 B-2.974 C180.000 F300 ; fig1_tan -15 (poly=105.0)
; END LINE
G1 X90.864 Y60.000 Z-60.035 B-0.638 C180.000 F300 ; STEP2 return angle=15 wp1
G1 X10.864 Y60.000 Z-60.035 B-0.638 C180.000 F300 ; STEP2 return angle=15 wp2
G1 X10.864 Y60.000 Z-110.035 B-0.638 C180.000 F300 ; STEP2 return angle=15 wp3
G1 X10.864 Y60.000 Z-110.035 B-0.638 C180.000 F300 ; STEP2 line 20 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=20 deg
G1 X50.864 Y60.000 Z-95.477 B-0.638 C180.000 F300 ; fig1_tan +20 (poly=20.0)
G1 X59.139 Y60.000 Z-105.424 B-3.099 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -20 (poly=110.0))
G1 X99.139 Y60.000 Z-119.983 B-3.099 C180.000 F300 ; fig1_tan -20 (poly=110.0)
; END LINE
G1 X91.736 Y60.000 Z-60.260 B-0.815 C180.000 F300 ; STEP2 return angle=20 wp1
G1 X11.736 Y60.000 Z-60.260 B-0.815 C180.000 F300 ; STEP2 return angle=20 wp2
G1 X11.736 Y60.000 Z-110.260 B-0.815 C180.000 F300 ; STEP2 return angle=20 wp3
G1 X11.736 Y60.000 Z-110.260 B-0.815 C180.000 F300 ; STEP2 line 25 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=25 deg
G1 X51.736 Y60.000 Z-91.607 B-0.815 C180.000 F300 ; fig1_tan +25 (poly=25.0)
G1 X59.252 Y60.000 Z-102.011 B-3.224 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -25 (poly=115.0))
G1 X99.252 Y60.000 Z-120.664 B-3.224 C180.000 F300 ; fig1_tan -25 (poly=115.0)
; END LINE
G1 X92.527 Y60.000 Z-60.572 B-0.981 C180.000 F300 ; STEP2 return angle=25 wp1
G1 X12.527 Y60.000 Z-60.572 B-0.981 C180.000 F300 ; STEP2 return angle=25 wp2
G1 X12.527 Y60.000 Z-110.572 B-0.981 C180.000 F300 ; STEP2 return angle=25 wp3
G1 X12.527 Y60.000 Z-110.572 B-0.981 C180.000 F300 ; STEP2 line 30 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=30 deg
G1 X52.527 Y60.000 Z-87.478 B-0.981 C180.000 F300 ; fig1_tan +30 (poly=30.0)
G1 X59.326 Y60.000 Z-98.250 B-3.350 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -30 (poly=120.0))
G1 X99.326 Y60.000 Z-121.344 B-3.350 C180.000 F300 ; fig1_tan -30 (poly=120.0)
; END LINE
G1 X93.250 Y60.000 Z-60.952 B-1.138 C180.000 F300 ; STEP2 return angle=30 wp1
G1 X13.250 Y60.000 Z-60.952 B-1.138 C180.000 F300 ; STEP2 return angle=30 wp2
G1 X13.250 Y60.000 Z-110.952 B-1.138 C180.000 F300 ; STEP2 return angle=30 wp3
G1 X13.250 Y60.000 Z-110.952 B-1.138 C180.000 F300 ; STEP2 line 35 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=35 deg
G1 X53.250 Y60.000 Z-82.944 B-1.138 C180.000 F300 ; fig1_tan +35 (poly=35.0)
G1 X59.359 Y60.000 Z-94.012 B-3.478 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -35 (poly=125.0))
G1 X99.359 Y60.000 Z-122.021 B-3.478 C180.000 F300 ; fig1_tan -35 (poly=125.0)
; END LINE
G1 X93.915 Y60.000 Z-61.387 B-1.288 C180.000 F300 ; STEP2 return angle=35 wp1
G1 X13.915 Y60.000 Z-61.387 B-1.288 C180.000 F300 ; STEP2 return angle=35 wp2
G1 X13.915 Y60.000 Z-111.387 B-1.288 C180.000 F300 ; STEP2 return angle=35 wp3
G1 X13.915 Y60.000 Z-111.387 B-1.288 C180.000 F300 ; STEP2 line 40 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=40 deg
G1 X53.915 Y60.000 Z-77.823 B-1.288 C180.000 F300 ; fig1_tan +40 (poly=40.0)
G1 X59.348 Y60.000 Z-89.129 B-3.608 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -40 (poly=130.0))
G1 X99.348 Y60.000 Z-122.693 B-3.608 C180.000 F300 ; fig1_tan -40 (poly=130.0)
; END LINE
G1 X94.530 Y60.000 Z-61.865 B-1.432 C180.000 F300 ; STEP2 return angle=40 wp1
G1 X14.530 Y60.000 Z-61.865 B-1.432 C180.000 F300 ; STEP2 return angle=40 wp2
G1 X14.530 Y60.000 Z-111.865 B-1.432 C180.000 F300 ; STEP2 return angle=40 wp3
G1 X14.530 Y60.000 Z-111.865 B-1.432 C180.000 F300 ; STEP2 line 45 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=45 deg
G1 X54.530 Y60.000 Z-71.865 B-1.432 C180.000 F300 ; fig1_tan +45 (poly=45.0)
G1 X59.289 Y60.000 Z-83.357 B-3.739 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -45 (poly=135.0))
G1 X99.289 Y60.000 Z-123.357 B-3.739 C180.000 F300 ; fig1_tan -45 (poly=135.0)
; END LINE
G1 X94.530 Y60.000 Z-61.865 B-1.432 C180.000 F300 ; STEP2 return angle=45 wp1
G1 X14.530 Y60.000 Z-61.865 B-1.432 C180.000 F300 ; STEP2 return angle=45 wp2
G1 X14.530 Y60.000 Z-111.865 B-1.432 C180.000 F300 ; STEP2 return angle=45 wp3
; === STEP 3: Figure 3 on first XZ plane (Y=start_y), non-tangential ===
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom-half origin (Y=start_y)
; BEGIN LINE: STEP3 bottom-half geom=135 deg
G1 X67.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 135deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 135 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 135 wp2
; BEGIN LINE: STEP3 bottom-half geom=130 deg
G1 X73.982 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 130deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 130 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 130 wp2
; BEGIN LINE: STEP3 bottom-half geom=125 deg
G1 X79.538 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 125deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 125 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 125 wp2
; BEGIN LINE: STEP3 bottom-half geom=120 deg
G1 X84.452 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 120deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 120 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 120 wp2
; BEGIN LINE: STEP3 bottom-half geom=115 deg
G1 X88.894 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 115deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 115 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 115 wp2
; BEGIN LINE: STEP3 bottom-half geom=110 deg
G1 X92.987 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 110deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 110 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 110 wp2
; BEGIN LINE: STEP3 bottom-half geom=105 deg
G1 X96.828 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 105deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 105 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 105 wp2
; BEGIN LINE: STEP3 bottom-half geom=100 deg
G1 X100.493 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 100deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 100 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 100 wp2
; BEGIN LINE: STEP3 bottom-half geom=95 deg
G1 X104.046 Y40.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom 95deg
; END LINE
G1 X107.546 Y40.000 Z-70.315 B0.000 C180.000 F300 ; STEP3 bottom return 95 wp1
G1 X107.546 Y40.000 Z-110.315 B0.000 C180.000 F300 ; STEP3 bottom return 95 wp2
; BEGIN LINE: STEP3 bottom-half geom=90 deg
G1 X107.546 Y40.000 Z-30.315 B0.000 C180.000 F300 ; fig3 bottom 90deg
; END LINE
; STEP3 top-half (non-tangential): move to end of 95deg line, then draw 85..45deg lines to top vertex; C=0
G1 C0.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X128.955 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 95 endpoint wp1
G1 X128.955 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 95 endpoint wp2
; BEGIN LINE: STEP3 top-half line=85 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 85deg (from 95 endpoint)
; END LINE
G1 X125.401 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 100 endpoint wp1
G1 X125.401 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 100 endpoint wp2
; BEGIN LINE: STEP3 top-half line=80 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 80deg (from 100 endpoint)
; END LINE
G1 X121.736 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 105 endpoint wp1
G1 X121.736 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 105 endpoint wp2
; BEGIN LINE: STEP3 top-half line=75 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 75deg (from 105 endpoint)
; END LINE
G1 X117.895 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 110 endpoint wp1
G1 X117.895 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 110 endpoint wp2
; BEGIN LINE: STEP3 top-half line=70 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 70deg (from 110 endpoint)
; END LINE
G1 X113.802 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 115 endpoint wp1
G1 X113.802 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 115 endpoint wp2
; BEGIN LINE: STEP3 top-half line=65 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 65deg (from 115 endpoint)
; END LINE
G1 X109.360 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 120 endpoint wp1
G1 X109.360 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 120 endpoint wp2
; BEGIN LINE: STEP3 top-half line=60 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 60deg (from 120 endpoint)
; END LINE
G1 X104.446 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 125 endpoint wp1
G1 X104.446 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 125 endpoint wp2
; BEGIN LINE: STEP3 top-half line=55 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 55deg (from 125 endpoint)
; END LINE
G1 X98.890 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 130 endpoint wp1
G1 X98.890 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 130 endpoint wp2
; BEGIN LINE: STEP3 top-half line=50 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 50deg (from 130 endpoint)
; END LINE
G1 X92.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; STEP3 top reposition to 135 endpoint wp1
G1 X92.454 Y40.000 Z-70.315 B0.000 C0.000 F300 ; STEP3 top reposition to 135 endpoint wp2
; BEGIN LINE: STEP3 top-half line=45 deg
G1 X132.454 Y40.000 Z-30.315 B0.000 C0.000 F300 ; fig3 top 45deg (from 135 endpoint)
; END LINE
; === STEP 4: Figure 3 bottom half on second XZ plane (Y=start_y+20), tangential ===
G1 C180.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X114.530 Y60.000 Z-111.865 B-1.432 C180.000 F300 ; STEP4 bottom-half origin (Y+20)
G1 X114.530 Y60.000 Z-111.865 B-1.432 C180.000 F300 ; STEP4 line 135 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=135 deg
G1 X74.530 Y60.000 Z-71.865 B-1.432 C180.000 F300 ; fig3 bottom tan 135deg (poly=45.0)
; END LINE
G1 X113.915 Y60.000 Z-71.387 B-1.288 C180.000 F300 ; STEP4 bottom return 135 wp1
G1 X113.915 Y60.000 Z-111.387 B-1.288 C180.000 F300 ; STEP4 bottom return 135 wp2
G1 X113.915 Y60.000 Z-111.387 B-1.288 C180.000 F300 ; STEP4 line 130 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=130 deg
G1 X80.351 Y60.000 Z-71.387 B-1.288 C180.000 F300 ; fig3 bottom tan 130deg (poly=40.0)
; END LINE
G1 X113.250 Y60.000 Z-70.952 B-1.138 C180.000 F300 ; STEP4 bottom return 130 wp1
G1 X113.250 Y60.000 Z-110.952 B-1.138 C180.000 F300 ; STEP4 bottom return 130 wp2
G1 X113.250 Y60.000 Z-110.952 B-1.138 C180.000 F300 ; STEP4 line 125 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=125 deg
G1 X85.241 Y60.000 Z-70.952 B-1.138 C180.000 F300 ; fig3 bottom tan 125deg (poly=35.0)
; END LINE
G1 X112.527 Y60.000 Z-70.572 B-0.981 C180.000 F300 ; STEP4 bottom return 125 wp1
G1 X112.527 Y60.000 Z-110.572 B-0.981 C180.000 F300 ; STEP4 bottom return 125 wp2
G1 X112.527 Y60.000 Z-110.572 B-0.981 C180.000 F300 ; STEP4 line 120 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=120 deg
G1 X89.433 Y60.000 Z-70.572 B-0.981 C180.000 F300 ; fig3 bottom tan 120deg (poly=30.0)
; END LINE
G1 X111.736 Y60.000 Z-70.260 B-0.815 C180.000 F300 ; STEP4 bottom return 120 wp1
G1 X111.736 Y60.000 Z-110.260 B-0.815 C180.000 F300 ; STEP4 bottom return 120 wp2
G1 X111.736 Y60.000 Z-110.260 B-0.815 C180.000 F300 ; STEP4 line 115 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=115 deg
G1 X93.084 Y60.000 Z-70.260 B-0.815 C180.000 F300 ; fig3 bottom tan 115deg (poly=25.0)
; END LINE
G1 X110.864 Y60.000 Z-70.035 B-0.638 C180.000 F300 ; STEP4 bottom return 115 wp1
G1 X110.864 Y60.000 Z-110.035 B-0.638 C180.000 F300 ; STEP4 bottom return 115 wp2
G1 X110.864 Y60.000 Z-110.035 B-0.638 C180.000 F300 ; STEP4 line 110 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=110 deg
G1 X96.305 Y60.000 Z-70.035 B-0.638 C180.000 F300 ; fig3 bottom tan 110deg (poly=20.0)
; END LINE
G1 X109.885 Y60.000 Z-69.932 B-0.445 C180.000 F300 ; STEP4 bottom return 110 wp1
G1 X109.885 Y60.000 Z-109.932 B-0.445 C180.000 F300 ; STEP4 bottom return 110 wp2
G1 X109.885 Y60.000 Z-109.932 B-0.445 C180.000 F300 ; STEP4 line 105 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=105 deg
G1 X99.167 Y60.000 Z-69.932 B-0.445 C180.000 F300 ; fig3 bottom tan 105deg (poly=15.0)
; END LINE
G1 X108.758 Y60.000 Z-70.004 B-0.228 C180.000 F300 ; STEP4 bottom return 105 wp1
G1 X108.758 Y60.000 Z-110.004 B-0.228 C180.000 F300 ; STEP4 bottom return 105 wp2
G1 X108.758 Y60.000 Z-110.004 B-0.228 C180.000 F300 ; STEP4 line 100 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=100 deg
G1 X101.705 Y60.000 Z-70.004 B-0.228 C180.000 F300 ; fig3 bottom tan 100deg (poly=10.0)
; END LINE
G1 X107.546 Y60.000 Z-70.315 B0.000 C180.000 F300 ; STEP4 bottom return 100 wp1
G1 X107.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP4 bottom return 100 wp2
G1 X107.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP4 line 95 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=95 deg
G1 X104.046 Y60.000 Z-70.315 B0.000 C180.000 F300 ; fig3 bottom tan 95deg (poly=5.0)
; END LINE
G1 X107.546 Y60.000 Z-70.315 B0.000 C180.000 F300 ; STEP4 bottom return 95 wp1
G1 X107.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP4 bottom return 95 wp2
G1 X107.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP4 line 90 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=90 deg
G1 X107.546 Y60.000 Z-30.315 B0.000 C180.000 F300 ; fig3 bottom tan 90deg (poly=0.0)
; END LINE
G1 X107.546 Y60.000 Z-30.315 B0.000 C180.000 F300 ; STEP4 bottom return 90 wp1
G1 X107.546 Y60.000 Z-110.315 B0.000 C180.000 F300 ; STEP4 bottom return 90 wp2
; === STEP 5: Figure 3 top half on third XZ plane (Y=start_y+40), tangential ===
G1 C0.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X124.883 Y80.000 Z-48.290 B-5.174 C0.000 F300 ; STEP5 top-half top vertex (Y+40)
G1 X124.883 Y80.000 Z-48.290 B-5.174 C0.000 F300 ; STEP5 line base=90 start position
; BEGIN LINE: STEP5 top-half tangential base=90 deg (top geom=270)
G1 X124.883 Y80.000 Z-88.290 B-5.174 C0.000 F300 ; fig3 top tan base=90 topgeom=270.0 (poly=180.0)
; END LINE
G1 X123.860 Y80.000 Z-47.943 B-4.971 C0.000 F300 ; STEP5 top return base=90 wp1
G1 X123.860 Y80.000 Z-47.943 B-4.971 C0.000 F300 ; STEP5 top return base=90 wp2
G1 X123.860 Y80.000 Z-47.943 B-4.971 C0.000 F300 ; STEP5 line base=95 start position
; BEGIN LINE: STEP5 top-half tangential base=95 deg (top geom=265)
G1 X120.360 Y80.000 Z-87.943 B-4.971 C0.000 F300 ; fig3 top tan base=95 topgeom=265.0 (poly=175.0)
; END LINE
G1 X119.564 Y80.000 Z-47.506 B-4.786 C0.000 F300 ; STEP5 top return base=95 wp1
G1 X123.064 Y80.000 Z-47.506 B-4.786 C0.000 F300 ; STEP5 top return base=95 wp2
G1 X123.064 Y80.000 Z-47.506 B-4.786 C0.000 F300 ; STEP5 line base=100 start position
; BEGIN LINE: STEP5 top-half tangential base=100 deg (top geom=260)
G1 X116.010 Y80.000 Z-87.506 B-4.786 C0.000 F300 ; fig3 top tan base=100 topgeom=260.0 (poly=170.0)
; END LINE
G1 X115.381 Y80.000 Z-47.008 B-4.615 C0.000 F300 ; STEP5 top return base=100 wp1
G1 X122.434 Y80.000 Z-47.008 B-4.615 C0.000 F300 ; STEP5 top return base=100 wp2
G1 X122.434 Y80.000 Z-47.008 B-4.615 C0.000 F300 ; STEP5 line base=105 start position
; BEGIN LINE: STEP5 top-half tangential base=105 deg (top geom=255)
G1 X111.716 Y80.000 Z-87.008 B-4.615 C0.000 F300 ; fig3 top tan base=105 topgeom=255.0 (poly=165.0)
; END LINE
G1 X111.215 Y80.000 Z-46.464 B-4.454 C0.000 F300 ; STEP5 top return base=105 wp1
G1 X121.933 Y80.000 Z-46.464 B-4.454 C0.000 F300 ; STEP5 top return base=105 wp2
G1 X121.933 Y80.000 Z-46.464 B-4.454 C0.000 F300 ; STEP5 line base=110 start position
; BEGIN LINE: STEP5 top-half tangential base=110 deg (top geom=250)
G1 X107.374 Y80.000 Z-86.464 B-4.454 C0.000 F300 ; fig3 top tan base=110 topgeom=250.0 (poly=160.0)
; END LINE
G1 X106.977 Y80.000 Z-45.886 B-4.301 C0.000 F300 ; STEP5 top return base=110 wp1
G1 X121.536 Y80.000 Z-45.886 B-4.301 C0.000 F300 ; STEP5 top return base=110 wp2
G1 X121.536 Y80.000 Z-45.886 B-4.301 C0.000 F300 ; STEP5 line base=115 start position
; BEGIN LINE: STEP5 top-half tangential base=115 deg (top geom=245)
G1 X102.884 Y80.000 Z-85.886 B-4.301 C0.000 F300 ; fig3 top tan base=115 topgeom=245.0 (poly=155.0)
; END LINE
G1 X102.575 Y80.000 Z-45.281 B-4.154 C0.000 F300 ; STEP5 top return base=115 wp1
G1 X121.227 Y80.000 Z-45.281 B-4.154 C0.000 F300 ; STEP5 top return base=115 wp2
G1 X121.227 Y80.000 Z-45.281 B-4.154 C0.000 F300 ; STEP5 line base=120 start position
; BEGIN LINE: STEP5 top-half tangential base=120 deg (top geom=240)
G1 X98.133 Y80.000 Z-85.281 B-4.154 C0.000 F300 ; fig3 top tan base=120 topgeom=240.0 (poly=150.0)
; END LINE
G1 X97.898 Y80.000 Z-44.655 B-4.012 C0.000 F300 ; STEP5 top return base=120 wp1
G1 X120.992 Y80.000 Z-44.655 B-4.012 C0.000 F300 ; STEP5 top return base=120 wp2
G1 X120.992 Y80.000 Z-44.655 B-4.012 C0.000 F300 ; STEP5 line base=125 start position
; BEGIN LINE: STEP5 top-half tangential base=125 deg (top geom=235)
G1 X92.984 Y80.000 Z-84.655 B-4.012 C0.000 F300 ; fig3 top tan base=125 topgeom=235.0 (poly=145.0)
; END LINE
G1 X92.814 Y80.000 Z-44.013 B-3.874 C0.000 F300 ; STEP5 top return base=125 wp1
G1 X120.823 Y80.000 Z-44.013 B-3.874 C0.000 F300 ; STEP5 top return base=125 wp2
G1 X120.823 Y80.000 Z-44.013 B-3.874 C0.000 F300 ; STEP5 line base=130 start position
; BEGIN LINE: STEP5 top-half tangential base=130 deg (top geom=230)
G1 X87.259 Y80.000 Z-84.013 B-3.874 C0.000 F300 ; fig3 top tan base=130 topgeom=230.0 (poly=140.0)
; END LINE
G1 X87.147 Y80.000 Z-43.357 B-3.739 C0.000 F300 ; STEP5 top return base=130 wp1
G1 X120.711 Y80.000 Z-43.357 B-3.739 C0.000 F300 ; STEP5 top return base=130 wp2
G1 X120.711 Y80.000 Z-43.357 B-3.739 C0.000 F300 ; STEP5 line base=135 start position
; BEGIN LINE: STEP5 top-half tangential base=135 deg (top geom=225)
G1 X80.711 Y80.000 Z-83.357 B-3.739 C0.000 F300 ; fig3 top tan base=135 topgeom=225.0 (poly=135.0)
; END LINE
; total printed length = 3661.496 mm
; printed line count = 59
; B-solve warnings = 4
; STEP2 first line a=0 target poly=0.0 err=5.498 deg
; fig1_tan a=0: target poly angle 0.000 deg, solved B=0.0000, abs error=5.498 deg
; STEP4 next-line preposition theta=90 target poly=0.0 err=5.498 deg
; fig3 bottom tan 90deg: target poly angle 0.000 deg, solved B=0.0000, abs error=5.498 deg
; end of program
