; generated by generate_custom_xz_geometry.py
; Custom XZ-plane geometry with optional tangential B-pull based on calibration tip-angle polynomial
; C-only moves use c_feed; XYZ/B moves use motion/print feed
; Axes: X=X Y=Y Z=Z B=B C=C U=U
; Calibration B range: [-5.200, 0.000]
; C(180) command from calibration: 180.000
; Feeds: motion=300.0, print=300.0, C-only=5000.0
; Extrusion disabled (set --extrusion-per-mm > 0 to emit U-axis commands)
; NOTE: Step 4 prompt had contradictory C setting; default bottom-half tangential C uses 180 (configurable)
G90
; === STEP 1: Figure 1 on first XZ plane (Y=start_y), non-tangential, B=0, C=0 ===
G1 C0.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; move to step1 start
; BEGIN LINE: STEP1 Figure1 angle=0 deg
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 a=0
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=0 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=0 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=0 wp3
; BEGIN LINE: STEP1 Figure1 angle=5 deg
G1 X79.419 Y40.000 Z-106.954 B0.000 C0.000 F300 ; fig1 +5
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -5
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=5 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=5 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=5 wp3
; BEGIN LINE: STEP1 Figure1 angle=10 deg
G1 X79.419 Y40.000 Z-103.400 B0.000 C0.000 F300 ; fig1 +10
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -10
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=10 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=10 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=10 wp3
; BEGIN LINE: STEP1 Figure1 angle=15 deg
G1 X79.419 Y40.000 Z-99.736 B0.000 C0.000 F300 ; fig1 +15
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -15
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=15 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=15 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=15 wp3
; BEGIN LINE: STEP1 Figure1 angle=20 deg
G1 X79.419 Y40.000 Z-95.895 B0.000 C0.000 F300 ; fig1 +20
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -20
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=20 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=20 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=20 wp3
; BEGIN LINE: STEP1 Figure1 angle=25 deg
G1 X79.419 Y40.000 Z-91.801 B0.000 C0.000 F300 ; fig1 +25
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -25
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=25 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=25 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=25 wp3
; BEGIN LINE: STEP1 Figure1 angle=30 deg
G1 X79.419 Y40.000 Z-87.360 B0.000 C0.000 F300 ; fig1 +30
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -30
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=30 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=30 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=30 wp3
; BEGIN LINE: STEP1 Figure1 angle=35 deg
G1 X79.419 Y40.000 Z-82.445 B0.000 C0.000 F300 ; fig1 +35
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -35
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=35 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=35 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=35 wp3
; BEGIN LINE: STEP1 Figure1 angle=40 deg
G1 X79.419 Y40.000 Z-76.890 B0.000 C0.000 F300 ; fig1 +40
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -40
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=40 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=40 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=40 wp3
; BEGIN LINE: STEP1 Figure1 angle=45 deg
G1 X79.419 Y40.000 Z-70.454 B0.000 C0.000 F300 ; fig1 +45
G1 X119.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; fig1 -45
; END LINE
G1 X119.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=45 wp1
G1 X39.419 Y40.000 Z-60.454 B0.000 C0.000 F300 ; STEP1 return angle=45 wp2
G1 X39.419 Y40.000 Z-110.454 B0.000 C0.000 F300 ; STEP1 return angle=45 wp3
; === STEP 2: Figure 1 on second XZ plane (Y=start_y+20), tangential, C=180 ===
G1 C180.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X0.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; move to step2 start (Y+20 plane)
G1 X0.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP2 line 0 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=0 deg
G1 X80.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; fig1_tan a=0 (poly=0.0)
; END LINE
G1 X80.581 Y60.000 Z-60.454 B0.000 C180.000 F300 ; STEP2 return angle=0 wp1
G1 X0.581 Y60.000 Z-60.454 B0.000 C180.000 F300 ; STEP2 return angle=0 wp2
G1 X0.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP2 return angle=0 wp3
G1 X0.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP2 line 5 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=5 deg
G1 X40.581 Y60.000 Z-106.954 B0.000 C180.000 F300 ; fig1_tan +5 (poly=5.0)
G1 X58.295 Y60.000 Z-119.836 B-2.602 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -5 (poly=95.0))
G1 X98.295 Y60.000 Z-123.336 B-2.602 C180.000 F300 ; fig1_tan -5 (poly=95.0)
; END LINE
G1 X80.930 Y60.000 Z-60.363 B-0.036 C180.000 F300 ; STEP2 return angle=5 wp1
G1 X0.930 Y60.000 Z-60.363 B-0.036 C180.000 F300 ; STEP2 return angle=5 wp2
G1 X0.930 Y60.000 Z-110.363 B-0.036 C180.000 F300 ; STEP2 return angle=5 wp3
G1 X0.930 Y60.000 Z-110.363 B-0.036 C180.000 F300 ; STEP2 line 10 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=10 deg
G1 X40.930 Y60.000 Z-103.310 B-0.036 C180.000 F300 ; fig1_tan +10 (poly=10.0)
G1 X58.631 Y60.000 Z-117.425 B-2.725 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -10 (poly=100.0))
G1 X98.631 Y60.000 Z-124.478 B-2.725 C180.000 F300 ; fig1_tan -10 (poly=100.0)
; END LINE
G1 X83.271 Y60.000 Z-60.017 B-0.280 C180.000 F300 ; STEP2 return angle=10 wp1
G1 X3.271 Y60.000 Z-60.017 B-0.280 C180.000 F300 ; STEP2 return angle=10 wp2
G1 X3.271 Y60.000 Z-110.017 B-0.280 C180.000 F300 ; STEP2 return angle=10 wp3
G1 X3.271 Y60.000 Z-110.017 B-0.280 C180.000 F300 ; STEP2 line 15 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=15 deg
G1 X43.271 Y60.000 Z-99.299 B-0.280 C180.000 F300 ; fig1_tan +15 (poly=15.0)
G1 X58.911 Y60.000 Z-114.908 B-2.848 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -15 (poly=105.0))
G1 X98.911 Y60.000 Z-125.626 B-2.848 C180.000 F300 ; fig1_tan -15 (poly=105.0)
; END LINE
G1 X85.178 Y60.000 Z-60.085 B-0.488 C180.000 F300 ; STEP2 return angle=15 wp1
G1 X5.178 Y60.000 Z-60.085 B-0.488 C180.000 F300 ; STEP2 return angle=15 wp2
G1 X5.178 Y60.000 Z-110.085 B-0.488 C180.000 F300 ; STEP2 return angle=15 wp3
G1 X5.178 Y60.000 Z-110.085 B-0.488 C180.000 F300 ; STEP2 line 20 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=20 deg
G1 X45.178 Y60.000 Z-95.526 B-0.488 C180.000 F300 ; fig1_tan +20 (poly=20.0)
G1 X59.134 Y60.000 Z-112.220 B-2.972 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -20 (poly=110.0))
G1 X99.134 Y60.000 Z-126.779 B-2.972 C180.000 F300 ; fig1_tan -20 (poly=110.0)
; END LINE
G1 X86.810 Y60.000 Z-60.405 B-0.675 C180.000 F300 ; STEP2 return angle=20 wp1
G1 X6.810 Y60.000 Z-60.405 B-0.675 C180.000 F300 ; STEP2 return angle=20 wp2
G1 X6.810 Y60.000 Z-110.405 B-0.675 C180.000 F300 ; STEP2 return angle=20 wp3
G1 X6.810 Y60.000 Z-110.405 B-0.675 C180.000 F300 ; STEP2 line 25 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=25 deg
G1 X46.810 Y60.000 Z-91.752 B-0.675 C180.000 F300 ; fig1_tan +25 (poly=25.0)
G1 X59.300 Y60.000 Z-109.281 B-3.097 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -25 (poly=115.0))
G1 X99.300 Y60.000 Z-127.933 B-3.097 C180.000 F300 ; fig1_tan -25 (poly=115.0)
; END LINE
G1 X88.245 Y60.000 Z-60.899 B-0.847 C180.000 F300 ; STEP2 return angle=25 wp1
G1 X8.245 Y60.000 Z-60.899 B-0.847 C180.000 F300 ; STEP2 return angle=25 wp2
G1 X8.245 Y60.000 Z-110.899 B-0.847 C180.000 F300 ; STEP2 return angle=25 wp3
G1 X8.245 Y60.000 Z-110.899 B-0.847 C180.000 F300 ; STEP2 line 30 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=30 deg
G1 X48.245 Y60.000 Z-87.805 B-0.847 C180.000 F300 ; fig1_tan +30 (poly=30.0)
G1 X59.405 Y60.000 Z-105.992 B-3.223 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -30 (poly=120.0))
G1 X99.405 Y60.000 Z-129.086 B-3.223 C180.000 F300 ; fig1_tan -30 (poly=120.0)
; END LINE
G1 X89.526 Y60.000 Z-61.523 B-1.008 C180.000 F300 ; STEP2 return angle=30 wp1
G1 X9.526 Y60.000 Z-61.523 B-1.008 C180.000 F300 ; STEP2 return angle=30 wp2
G1 X9.526 Y60.000 Z-111.523 B-1.008 C180.000 F300 ; STEP2 return angle=30 wp3
G1 X9.526 Y60.000 Z-111.523 B-1.008 C180.000 F300 ; STEP2 line 35 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=35 deg
G1 X49.526 Y60.000 Z-83.514 B-1.008 C180.000 F300 ; fig1_tan +35 (poly=35.0)
G1 X59.446 Y60.000 Z-102.227 B-3.350 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -35 (poly=125.0))
G1 X99.446 Y60.000 Z-130.235 B-3.350 C180.000 F300 ; fig1_tan -35 (poly=125.0)
; END LINE
G1 X90.683 Y60.000 Z-62.246 B-1.161 C180.000 F300 ; STEP2 return angle=35 wp1
G1 X10.683 Y60.000 Z-62.246 B-1.161 C180.000 F300 ; STEP2 return angle=35 wp2
G1 X10.683 Y60.000 Z-112.246 B-1.161 C180.000 F300 ; STEP2 return angle=35 wp3
G1 X10.683 Y60.000 Z-112.246 B-1.161 C180.000 F300 ; STEP2 line 40 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=40 deg
G1 X50.683 Y60.000 Z-78.682 B-1.161 C180.000 F300 ; fig1_tan +40 (poly=40.0)
G1 X59.420 Y60.000 Z-97.811 B-3.479 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -40 (poly=130.0))
G1 X99.420 Y60.000 Z-131.375 B-3.479 C180.000 F300 ; fig1_tan -40 (poly=130.0)
; END LINE
G1 X91.735 Y60.000 Z-63.047 B-1.307 C180.000 F300 ; STEP2 return angle=40 wp1
G1 X11.735 Y60.000 Z-63.047 B-1.307 C180.000 F300 ; STEP2 return angle=40 wp2
G1 X11.735 Y60.000 Z-113.047 B-1.307 C180.000 F300 ; STEP2 return angle=40 wp3
G1 X11.735 Y60.000 Z-113.047 B-1.307 C180.000 F300 ; STEP2 line 45 start position
; BEGIN LINE: STEP2 Figure1 tangential angle=45 deg
G1 X51.735 Y60.000 Z-73.047 B-1.307 C180.000 F300 ; fig1_tan +45 (poly=45.0)
G1 X59.321 Y60.000 Z-92.504 B-3.611 C180.000 F300 ; tip-fixed pivot to next piece (fig1_tan -45 (poly=135.0))
G1 X99.321 Y60.000 Z-132.504 B-3.611 C180.000 F300 ; fig1_tan -45 (poly=135.0)
; END LINE
G1 X91.735 Y60.000 Z-63.047 B-1.307 C180.000 F300 ; STEP2 return angle=45 wp1
G1 X11.735 Y60.000 Z-63.047 B-1.307 C180.000 F300 ; STEP2 return angle=45 wp2
G1 X11.735 Y60.000 Z-113.047 B-1.307 C180.000 F300 ; STEP2 return angle=45 wp3
; === STEP 3: Figure 3 on first XZ plane (Y=start_y), non-tangential ===
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom-half origin (Y=start_y)
; BEGIN LINE: STEP3 bottom-half geom=135 deg
G1 X60.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 135deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 135 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 135 wp2
; BEGIN LINE: STEP3 bottom-half geom=130 deg
G1 X67.017 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 130deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 130 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 130 wp2
; BEGIN LINE: STEP3 bottom-half geom=125 deg
G1 X72.572 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 125deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 125 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 125 wp2
; BEGIN LINE: STEP3 bottom-half geom=120 deg
G1 X77.487 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 120deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 120 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 120 wp2
; BEGIN LINE: STEP3 bottom-half geom=115 deg
G1 X81.928 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 115deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 115 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 115 wp2
; BEGIN LINE: STEP3 bottom-half geom=110 deg
G1 X86.022 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 110deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 110 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 110 wp2
; BEGIN LINE: STEP3 bottom-half geom=105 deg
G1 X89.863 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 105deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 105 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 105 wp2
; BEGIN LINE: STEP3 bottom-half geom=100 deg
G1 X93.527 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 100deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 100 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 100 wp2
; BEGIN LINE: STEP3 bottom-half geom=95 deg
G1 X97.081 Y40.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom 95deg
; END LINE
G1 X100.581 Y40.000 Z-70.454 B0.000 C180.000 F300 ; STEP3 bottom return 95 wp1
G1 X100.581 Y40.000 Z-110.454 B0.000 C180.000 F300 ; STEP3 bottom return 95 wp2
; BEGIN LINE: STEP3 bottom-half geom=90 deg
G1 X100.581 Y40.000 Z-30.454 B0.000 C180.000 F300 ; fig3 bottom 90deg
; END LINE
; STEP3 top-half (non-tangential): move to end of 95deg line, then draw 85..45deg lines to top vertex; C=0
G1 C0.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X135.920 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 95 endpoint wp1
G1 X135.920 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 95 endpoint wp2
; BEGIN LINE: STEP3 top-half line=85 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 85deg (from 95 endpoint)
; END LINE
G1 X132.366 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 100 endpoint wp1
G1 X132.366 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 100 endpoint wp2
; BEGIN LINE: STEP3 top-half line=80 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 80deg (from 100 endpoint)
; END LINE
G1 X128.702 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 105 endpoint wp1
G1 X128.702 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 105 endpoint wp2
; BEGIN LINE: STEP3 top-half line=75 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 75deg (from 105 endpoint)
; END LINE
G1 X124.861 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 110 endpoint wp1
G1 X124.861 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 110 endpoint wp2
; BEGIN LINE: STEP3 top-half line=70 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 70deg (from 110 endpoint)
; END LINE
G1 X120.767 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 115 endpoint wp1
G1 X120.767 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 115 endpoint wp2
; BEGIN LINE: STEP3 top-half line=65 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 65deg (from 115 endpoint)
; END LINE
G1 X116.325 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 120 endpoint wp1
G1 X116.325 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 120 endpoint wp2
; BEGIN LINE: STEP3 top-half line=60 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 60deg (from 120 endpoint)
; END LINE
G1 X111.411 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 125 endpoint wp1
G1 X111.411 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 125 endpoint wp2
; BEGIN LINE: STEP3 top-half line=55 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 55deg (from 125 endpoint)
; END LINE
G1 X105.855 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 130 endpoint wp1
G1 X105.855 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 130 endpoint wp2
; BEGIN LINE: STEP3 top-half line=50 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 50deg (from 130 endpoint)
; END LINE
G1 X99.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; STEP3 top reposition to 135 endpoint wp1
G1 X99.419 Y40.000 Z-70.454 B0.000 C0.000 F300 ; STEP3 top reposition to 135 endpoint wp2
; BEGIN LINE: STEP3 top-half line=45 deg
G1 X139.419 Y40.000 Z-30.454 B0.000 C0.000 F300 ; fig3 top 45deg (from 135 endpoint)
; END LINE
; === STEP 4: Figure 3 bottom half on second XZ plane (Y=start_y+20), tangential ===
G1 C180.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X111.735 Y60.000 Z-113.047 B-1.307 C180.000 F300 ; STEP4 bottom-half origin (Y+20)
G1 X111.735 Y60.000 Z-113.047 B-1.307 C180.000 F300 ; STEP4 line 135 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=135 deg
G1 X71.735 Y60.000 Z-73.047 B-1.307 C180.000 F300 ; fig3 bottom tan 135deg (poly=45.0)
; END LINE
G1 X110.683 Y60.000 Z-72.246 B-1.161 C180.000 F300 ; STEP4 bottom return 135 wp1
G1 X110.683 Y60.000 Z-112.246 B-1.161 C180.000 F300 ; STEP4 bottom return 135 wp2
G1 X110.683 Y60.000 Z-112.246 B-1.161 C180.000 F300 ; STEP4 line 130 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=130 deg
G1 X77.119 Y60.000 Z-72.246 B-1.161 C180.000 F300 ; fig3 bottom tan 130deg (poly=40.0)
; END LINE
G1 X109.526 Y60.000 Z-71.523 B-1.008 C180.000 F300 ; STEP4 bottom return 130 wp1
G1 X109.526 Y60.000 Z-111.523 B-1.008 C180.000 F300 ; STEP4 bottom return 130 wp2
G1 X109.526 Y60.000 Z-111.523 B-1.008 C180.000 F300 ; STEP4 line 125 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=125 deg
G1 X81.518 Y60.000 Z-71.523 B-1.008 C180.000 F300 ; fig3 bottom tan 125deg (poly=35.0)
; END LINE
G1 X108.245 Y60.000 Z-70.899 B-0.847 C180.000 F300 ; STEP4 bottom return 125 wp1
G1 X108.245 Y60.000 Z-110.899 B-0.847 C180.000 F300 ; STEP4 bottom return 125 wp2
G1 X108.245 Y60.000 Z-110.899 B-0.847 C180.000 F300 ; STEP4 line 120 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=120 deg
G1 X85.151 Y60.000 Z-70.899 B-0.847 C180.000 F300 ; fig3 bottom tan 120deg (poly=30.0)
; END LINE
G1 X106.810 Y60.000 Z-70.405 B-0.675 C180.000 F300 ; STEP4 bottom return 120 wp1
G1 X106.810 Y60.000 Z-110.405 B-0.675 C180.000 F300 ; STEP4 bottom return 120 wp2
G1 X106.810 Y60.000 Z-110.405 B-0.675 C180.000 F300 ; STEP4 line 115 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=115 deg
G1 X88.158 Y60.000 Z-70.405 B-0.675 C180.000 F300 ; fig3 bottom tan 115deg (poly=25.0)
; END LINE
G1 X105.178 Y60.000 Z-70.085 B-0.488 C180.000 F300 ; STEP4 bottom return 115 wp1
G1 X105.178 Y60.000 Z-110.085 B-0.488 C180.000 F300 ; STEP4 bottom return 115 wp2
G1 X105.178 Y60.000 Z-110.085 B-0.488 C180.000 F300 ; STEP4 line 110 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=110 deg
G1 X90.619 Y60.000 Z-70.085 B-0.488 C180.000 F300 ; fig3 bottom tan 110deg (poly=20.0)
; END LINE
G1 X103.271 Y60.000 Z-70.017 B-0.280 C180.000 F300 ; STEP4 bottom return 110 wp1
G1 X103.271 Y60.000 Z-110.017 B-0.280 C180.000 F300 ; STEP4 bottom return 110 wp2
G1 X103.271 Y60.000 Z-110.017 B-0.280 C180.000 F300 ; STEP4 line 105 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=105 deg
G1 X92.553 Y60.000 Z-70.017 B-0.280 C180.000 F300 ; fig3 bottom tan 105deg (poly=15.0)
; END LINE
G1 X100.930 Y60.000 Z-70.363 B-0.036 C180.000 F300 ; STEP4 bottom return 105 wp1
G1 X100.930 Y60.000 Z-110.363 B-0.036 C180.000 F300 ; STEP4 bottom return 105 wp2
G1 X100.930 Y60.000 Z-110.363 B-0.036 C180.000 F300 ; STEP4 line 100 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=100 deg
G1 X93.877 Y60.000 Z-70.363 B-0.036 C180.000 F300 ; fig3 bottom tan 100deg (poly=10.0)
; END LINE
G1 X100.581 Y60.000 Z-70.454 B0.000 C180.000 F300 ; STEP4 bottom return 100 wp1
G1 X100.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP4 bottom return 100 wp2
G1 X100.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP4 line 95 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=95 deg
G1 X97.081 Y60.000 Z-70.454 B0.000 C180.000 F300 ; fig3 bottom tan 95deg (poly=5.0)
; END LINE
G1 X100.581 Y60.000 Z-70.454 B0.000 C180.000 F300 ; STEP4 bottom return 95 wp1
G1 X100.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP4 bottom return 95 wp2
G1 X100.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP4 line 90 start position
; BEGIN LINE: STEP4 bottom-half tangential geom=90 deg
G1 X100.581 Y60.000 Z-30.454 B0.000 C180.000 F300 ; fig3 bottom tan 90deg (poly=0.0)
; END LINE
G1 X100.581 Y60.000 Z-30.454 B0.000 C180.000 F300 ; STEP4 bottom return 90 wp1
G1 X100.581 Y60.000 Z-110.454 B0.000 C180.000 F300 ; STEP4 bottom return 90 wp2
; === STEP 5: Figure 3 top half on third XZ plane (Y=start_y+40), tangential ===
G1 C0.000 F5000 ; fast C rotate before XYZ/B positioning
G1 X127.256 Y80.000 Z-60.819 B-5.085 C0.000 F300 ; STEP5 top-half top vertex (Y+40)
G1 X127.256 Y80.000 Z-60.819 B-5.085 C0.000 F300 ; STEP5 line base=90 start position
; BEGIN LINE: STEP5 top-half tangential base=90 deg (top geom=270)
G1 X127.256 Y80.000 Z-100.819 B-5.085 C0.000 F300 ; fig3 top tan base=90 topgeom=270.0 (poly=180.0)
; END LINE
G1 X125.599 Y80.000 Z-60.275 B-4.866 C0.000 F300 ; STEP5 top return base=90 wp1
G1 X125.599 Y80.000 Z-60.275 B-4.866 C0.000 F300 ; STEP5 top return base=90 wp2
G1 X125.599 Y80.000 Z-60.275 B-4.866 C0.000 F300 ; STEP5 line base=95 start position
; BEGIN LINE: STEP5 top-half tangential base=95 deg (top geom=265)
G1 X122.100 Y80.000 Z-100.275 B-4.866 C0.000 F300 ; fig3 top tan base=95 topgeom=265.0 (poly=175.0)
; END LINE
G1 X120.843 Y80.000 Z-59.551 B-4.672 C0.000 F300 ; STEP5 top return base=95 wp1
G1 X124.343 Y80.000 Z-59.551 B-4.672 C0.000 F300 ; STEP5 top return base=95 wp2
G1 X124.343 Y80.000 Z-59.551 B-4.672 C0.000 F300 ; STEP5 line base=100 start position
; BEGIN LINE: STEP5 top-half tangential base=100 deg (top geom=260)
G1 X117.290 Y80.000 Z-99.551 B-4.672 C0.000 F300 ; fig3 top tan base=100 topgeom=260.0 (poly=170.0)
; END LINE
G1 X116.308 Y80.000 Z-58.710 B-4.496 C0.000 F300 ; STEP5 top return base=100 wp1
G1 X123.361 Y80.000 Z-58.710 B-4.496 C0.000 F300 ; STEP5 top return base=100 wp2
G1 X123.361 Y80.000 Z-58.710 B-4.496 C0.000 F300 ; STEP5 line base=105 start position
; BEGIN LINE: STEP5 top-half tangential base=105 deg (top geom=255)
G1 X112.643 Y80.000 Z-98.710 B-4.496 C0.000 F300 ; fig3 top tan base=105 topgeom=255.0 (poly=165.0)
; END LINE
G1 X111.866 Y80.000 Z-57.787 B-4.331 C0.000 F300 ; STEP5 top return base=105 wp1
G1 X122.584 Y80.000 Z-57.787 B-4.331 C0.000 F300 ; STEP5 top return base=105 wp2
G1 X122.584 Y80.000 Z-57.787 B-4.331 C0.000 F300 ; STEP5 line base=110 start position
; BEGIN LINE: STEP5 top-half tangential base=110 deg (top geom=250)
G1 X108.025 Y80.000 Z-97.787 B-4.331 C0.000 F300 ; fig3 top tan base=110 topgeom=250.0 (poly=160.0)
; END LINE
G1 X107.412 Y80.000 Z-56.804 B-4.176 C0.000 F300 ; STEP5 top return base=110 wp1
G1 X121.971 Y80.000 Z-56.804 B-4.176 C0.000 F300 ; STEP5 top return base=110 wp2
G1 X121.971 Y80.000 Z-56.804 B-4.176 C0.000 F300 ; STEP5 line base=115 start position
; BEGIN LINE: STEP5 top-half tangential base=115 deg (top geom=245)
G1 X103.318 Y80.000 Z-96.804 B-4.176 C0.000 F300 ; fig3 top tan base=115 topgeom=245.0 (poly=155.0)
; END LINE
G1 X102.838 Y80.000 Z-55.774 B-4.027 C0.000 F300 ; STEP5 top return base=115 wp1
G1 X121.491 Y80.000 Z-55.774 B-4.027 C0.000 F300 ; STEP5 top return base=115 wp2
G1 X121.491 Y80.000 Z-55.774 B-4.027 C0.000 F300 ; STEP5 line base=120 start position
; BEGIN LINE: STEP5 top-half tangential base=120 deg (top geom=240)
G1 X98.397 Y80.000 Z-95.774 B-4.027 C0.000 F300 ; fig3 top tan base=120 topgeom=240.0 (poly=150.0)
; END LINE
G1 X98.031 Y80.000 Z-54.709 B-3.884 C0.000 F300 ; STEP5 top return base=120 wp1
G1 X121.125 Y80.000 Z-54.709 B-3.884 C0.000 F300 ; STEP5 top return base=120 wp2
G1 X121.125 Y80.000 Z-54.709 B-3.884 C0.000 F300 ; STEP5 line base=125 start position
; BEGIN LINE: STEP5 top-half tangential base=125 deg (top geom=235)
G1 X93.116 Y80.000 Z-94.709 B-3.884 C0.000 F300 ; fig3 top tan base=125 topgeom=235.0 (poly=145.0)
; END LINE
G1 X92.850 Y80.000 Z-53.617 B-3.746 C0.000 F300 ; STEP5 top return base=125 wp1
G1 X120.858 Y80.000 Z-53.617 B-3.746 C0.000 F300 ; STEP5 top return base=125 wp2
G1 X120.858 Y80.000 Z-53.617 B-3.746 C0.000 F300 ; STEP5 line base=130 start position
; BEGIN LINE: STEP5 top-half tangential base=130 deg (top geom=230)
G1 X87.294 Y80.000 Z-93.617 B-3.746 C0.000 F300 ; fig3 top tan base=130 topgeom=230.0 (poly=140.0)
; END LINE
G1 X87.115 Y80.000 Z-52.504 B-3.611 C0.000 F300 ; STEP5 top return base=130 wp1
G1 X120.679 Y80.000 Z-52.504 B-3.611 C0.000 F300 ; STEP5 top return base=130 wp2
G1 X120.679 Y80.000 Z-52.504 B-3.611 C0.000 F300 ; STEP5 line base=135 start position
; BEGIN LINE: STEP5 top-half tangential base=135 deg (top geom=225)
G1 X80.679 Y80.000 Z-92.504 B-3.611 C0.000 F300 ; fig3 top tan base=135 topgeom=225.0 (poly=135.0)
; END LINE
; total printed length = 3661.496 mm
; printed line count = 59
; B-solve warnings = 8
; STEP2 first line a=0 target poly=0.0 err=9.354 deg
; fig1_tan a=0: target poly angle 0.000 deg, solved B=0.0000, abs error=9.354 deg
; STEP2 next-line preposition a=5 target poly=5.0 err=4.354 deg
; fig1_tan +5: target poly angle 5.000 deg, solved B=0.0000, abs error=4.354 deg
; STEP4 next-line preposition theta=95 target poly=5.0 err=4.354 deg
; fig3 bottom tan 95deg: target poly angle 5.000 deg, solved B=0.0000, abs error=4.354 deg
; STEP4 next-line preposition theta=90 target poly=0.0 err=9.354 deg
; fig3 bottom tan 90deg: target poly angle 0.000 deg, solved B=0.0000, abs error=9.354 deg
; end of program
