; generated by tetrahedral_truss_tip_priority_tangent_soft.py
; strategy: exact tip position (hard) + tangent/nozzle angle alignment (soft)
; user tip-angle convention: angle measured FROM VERTICAL (horizontal line ~90 deg)
; head-front preference: choose edge direction so head/stage leads deposition point when possible
; build order heuristic: bottom-center-first, bottom-up, center-out
; geometry: double tetrahedron (mirrored along base plane)
; PHYSICAL tip kinematics unchanged; attack azimuth remap used only for tangency
; model assumptions:
;   physical tip_offset(B,C) = [r(B) cos(C), r(B) sin(C), z(B)]
;   nozzle attack dir(B,C) = [sin(a(B)) cos(theta_attack), sin(a(B)) sin(theta_attack), cos(a(B))]
;   theta_attack = C + +180.000 deg
;   a(B) = (+1.000) * tip_angle_poly(B) + +0.000 deg
; axes: X->X, Y->Y, Z->Z, B->B, C->C, U->U
; edges planned = 39 (all edges extruded exactly once)
; total print length ~ 585.000 mm
; total tip travel  ~ 403.543 mm
; tangent angle error [min/mean/max] = 0.044 / 0.049 / 0.057 deg
; head-lead [min/mean/max] mm = -4.464 / -3.220 / -1.229
; head-front ok / violations = 0 / 39
; B used range = [-2.521, -1.054]
; C used range = [-1950.000, 270.000]
; X gantry range used = [44.706, 85.294]
; Y gantry range used = [46.943, 82.094]
; Z gantry range used = [-115.640, -66.650]
; virtual bbox (enforced during print/travel): X[10.000, 110.000] Y[10.000, 110.000] Z[-120.000, -20.000]
; startup safe approach Z = 0.000
; start pose (stage) = [60.000, 40.000, -30.000, 0.000, 0.000]
; end pose (stage)   = [60.000, 40.000, -30.000, 0.000, 0.000]
; bottom-center start (tip-space heuristic origin) = [65.000, 58.660, -114.495]
; extrusion_per_mm = 0.020000 U/mm-path (coordinated with print feed)
; pressure_offset_mm = 3.000 U mm
; pressure advance/retract feeds = 120.0/240.0 mm/min on U
; preflow_dwell_ms = 700   node_dwell_ms = 700
G90
M82
G92 U0
; safe startup approach: Z first, then XY, then dive to start Z
G1 Z0.000 B0.000 C0.000 F1200
G1 X60.000 Y40.000 B0.000 C0.000 F1200
G1 Z-30.000 B0.000 C0.000 F1200
; --- edge 1/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=270.000, head_lead=-4.464 mm, head_front_ok=0
; startup move to first strut start (bottom-center-first ordering)
G1 X65.000 Y52.547 Z-115.640 B-1.054 C270.000 F1200
; pressure preload before print pass
G1 U3.000 F120
G4 P700
G1 X65.000 Y53.629 Z-114.109 B-1.054 C270.000 U3.038 F300
G1 X65.000 Y54.712 Z-112.578 B-1.054 C270.000 U3.075 F300
G1 X65.000 Y55.794 Z-111.047 B-1.054 C270.000 U3.113 F300
G1 X65.000 Y56.877 Z-109.516 B-1.054 C270.000 U3.150 F300
G1 X65.000 Y57.959 Z-107.985 B-1.054 C270.000 U3.188 F300
G1 X65.000 Y59.042 Z-106.454 B-1.054 C270.000 U3.225 F300
G1 X65.000 Y60.125 Z-104.923 B-1.054 C270.000 U3.262 F300
G1 X65.000 Y61.207 Z-103.392 B-1.054 C270.000 U3.300 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U0.300 F240
; --- edge 2/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=150.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X59.706 Y61.717 Z-115.640 B-1.054 C150.000 F1200
; pressure preload before print pass
G1 U3.300 F120
G4 P700
G1 X60.643 Y61.176 Z-114.109 B-1.054 C150.000 U3.337 F300
G1 X61.581 Y60.634 Z-112.578 B-1.054 C150.000 U3.375 F300
G1 X62.518 Y60.093 Z-111.047 B-1.054 C150.000 U3.413 F300
G1 X63.456 Y59.552 Z-109.516 B-1.054 C150.000 U3.450 F300
G1 X64.393 Y59.011 Z-107.985 B-1.054 C150.000 U3.487 F300
G1 X65.331 Y58.469 Z-106.454 B-1.054 C150.000 U3.525 F300
G1 X66.268 Y57.928 Z-104.923 B-1.054 C150.000 U3.562 F300
G1 X67.206 Y57.387 Z-103.392 B-1.054 C150.000 U3.600 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U0.600 F240
; --- edge 3/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=30.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X70.294 Y61.717 Z-115.640 B-1.054 C30.000 F1200
; pressure preload before print pass
G1 U3.600 F120
G4 P700
G1 X69.357 Y61.176 Z-114.109 B-1.054 C30.000 U3.638 F300
G1 X68.419 Y60.634 Z-112.578 B-1.054 C30.000 U3.675 F300
G1 X67.482 Y60.093 Z-111.047 B-1.054 C30.000 U3.712 F300
G1 X66.544 Y59.552 Z-109.516 B-1.054 C30.000 U3.750 F300
G1 X65.607 Y59.011 Z-107.985 B-1.054 C30.000 U3.787 F300
G1 X64.669 Y58.469 Z-106.454 B-1.054 C30.000 U3.825 F300
G1 X63.732 Y57.928 Z-104.923 B-1.054 C30.000 U3.862 F300
G1 X62.794 Y57.387 Z-103.392 B-1.054 C30.000 U3.900 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U0.900 F240
; --- edge 4/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-120.000, head_lead=-1.229 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X56.885 Y53.265 Z-109.697 B-2.521 C-120.000 F1200
; pressure preload before print pass
G1 U3.900 F120
G4 P700
G1 X57.823 Y54.889 Z-109.697 B-2.521 C-120.000 U3.937 F300
G1 X58.760 Y56.513 Z-109.697 B-2.521 C-120.000 U3.975 F300
G1 X59.698 Y58.137 Z-109.697 B-2.521 C-120.000 U4.012 F300
G1 X60.635 Y59.761 Z-109.697 B-2.521 C-120.000 U4.050 F300
G1 X61.573 Y61.384 Z-109.697 B-2.521 C-120.000 U4.087 F300
G1 X62.510 Y63.008 Z-109.697 B-2.521 C-120.000 U4.125 F300
G1 X63.448 Y64.632 Z-109.697 B-2.521 C-120.000 U4.162 F300
G1 X64.385 Y66.256 Z-109.697 B-2.521 C-120.000 U4.200 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 5/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-240.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X64.385 Y68.385 Z-109.697 B-2.521 C-240.000 F1200
G1 X65.323 Y66.761 Z-109.697 B-2.521 C-240.000 U4.237 F300
G1 X66.260 Y65.138 Z-109.697 B-2.521 C-240.000 U4.275 F300
G1 X67.198 Y63.514 Z-109.697 B-2.521 C-240.000 U4.312 F300
G1 X68.135 Y61.890 Z-109.697 B-2.521 C-240.000 U4.350 F300
G1 X69.073 Y60.266 Z-109.697 B-2.521 C-240.000 U4.387 F300
G1 X70.010 Y58.642 Z-109.697 B-2.521 C-240.000 U4.425 F300
G1 X70.948 Y57.019 Z-109.697 B-2.521 C-240.000 U4.462 F300
G1 X71.885 Y55.395 Z-109.697 B-2.521 C-240.000 U4.500 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 6/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-360.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X73.729 Y54.330 Z-109.697 B-2.521 C-360.000 F1200
G1 X71.854 Y54.330 Z-109.697 B-2.521 C-360.000 U4.537 F300
G1 X69.979 Y54.330 Z-109.697 B-2.521 C-360.000 U4.575 F300
G1 X68.104 Y54.330 Z-109.697 B-2.521 C-360.000 U4.612 F300
G1 X66.229 Y54.330 Z-109.697 B-2.521 C-360.000 U4.650 F300
G1 X64.354 Y54.330 Z-109.697 B-2.521 C-360.000 U4.688 F300
G1 X62.479 Y54.330 Z-109.697 B-2.521 C-360.000 U4.725 F300
G1 X60.604 Y54.330 Z-109.697 B-2.521 C-360.000 U4.763 F300
G1 X58.729 Y54.330 Z-109.697 B-2.521 C-360.000 U4.800 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U1.800 F240
; --- edge 7/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-210.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X59.706 Y70.377 Z-103.392 B-1.054 C-210.000 F1200
; pressure preload before print pass
G1 U4.800 F120
G4 P700
G1 X60.643 Y69.836 Z-101.861 B-1.054 C-210.000 U4.838 F300
G1 X61.581 Y69.295 Z-100.330 B-1.054 C-210.000 U4.875 F300
G1 X62.518 Y68.753 Z-98.799 B-1.054 C-210.000 U4.913 F300
G1 X63.456 Y68.212 Z-97.268 B-1.054 C-210.000 U4.950 F300
G1 X64.393 Y67.671 Z-95.737 B-1.054 C-210.000 U4.988 F300
G1 X65.331 Y67.130 Z-94.207 B-1.054 C-210.000 U5.025 F300
G1 X66.268 Y66.588 Z-92.676 B-1.054 C-210.000 U5.062 F300
G1 X67.206 Y66.047 Z-91.145 B-1.054 C-210.000 U5.100 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U2.100 F240
; --- edge 8/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-330.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X70.294 Y70.377 Z-103.392 B-1.054 C-330.000 F1200
; pressure preload before print pass
G1 U5.100 F120
G4 P700
G1 X69.357 Y69.836 Z-101.861 B-1.054 C-330.000 U5.138 F300
G1 X68.419 Y69.295 Z-100.330 B-1.054 C-330.000 U5.175 F300
G1 X67.482 Y68.753 Z-98.799 B-1.054 C-330.000 U5.213 F300
G1 X66.544 Y68.212 Z-97.268 B-1.054 C-330.000 U5.250 F300
G1 X65.607 Y67.671 Z-95.737 B-1.054 C-330.000 U5.288 F300
G1 X64.669 Y67.130 Z-94.207 B-1.054 C-330.000 U5.325 F300
G1 X63.732 Y66.588 Z-92.676 B-1.054 C-330.000 U5.363 F300
G1 X62.794 Y66.047 Z-91.145 B-1.054 C-330.000 U5.400 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U2.400 F240
; --- edge 9/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-210.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X52.206 Y57.387 Z-103.392 B-1.054 C-210.000 F1200
; pressure preload before print pass
G1 U5.400 F120
G4 P700
G1 X53.143 Y56.846 Z-101.861 B-1.054 C-210.000 U5.438 F300
G1 X54.081 Y56.304 Z-100.330 B-1.054 C-210.000 U5.475 F300
G1 X55.018 Y55.763 Z-98.799 B-1.054 C-210.000 U5.513 F300
G1 X55.956 Y55.222 Z-97.268 B-1.054 C-210.000 U5.550 F300
G1 X56.893 Y54.681 Z-95.737 B-1.054 C-210.000 U5.588 F300
G1 X57.831 Y54.139 Z-94.207 B-1.054 C-210.000 U5.625 F300
G1 X58.768 Y53.598 Z-92.676 B-1.054 C-210.000 U5.663 F300
G1 X59.706 Y53.057 Z-91.145 B-1.054 C-210.000 U5.700 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U2.700 F240
; --- edge 10/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-330.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X77.794 Y57.387 Z-103.392 B-1.054 C-330.000 F1200
; pressure preload before print pass
G1 U5.700 F120
G4 P700
G1 X76.857 Y56.846 Z-101.861 B-1.054 C-330.000 U5.738 F300
G1 X75.919 Y56.304 Z-100.330 B-1.054 C-330.000 U5.775 F300
G1 X74.982 Y55.763 Z-98.799 B-1.054 C-330.000 U5.813 F300
G1 X74.044 Y55.222 Z-97.268 B-1.054 C-330.000 U5.850 F300
G1 X73.107 Y54.681 Z-95.737 B-1.054 C-330.000 U5.888 F300
G1 X72.169 Y54.139 Z-94.207 B-1.054 C-330.000 U5.925 F300
G1 X71.232 Y53.598 Z-92.676 B-1.054 C-330.000 U5.963 F300
G1 X70.294 Y53.057 Z-91.145 B-1.054 C-330.000 U6.000 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U3.000 F240
; --- edge 11/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-450.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X72.500 Y48.217 Z-103.392 B-1.054 C-450.000 F1200
; pressure preload before print pass
G1 U6.000 F120
G4 P700
G1 X72.500 Y49.299 Z-101.861 B-1.054 C-450.000 U6.038 F300
G1 X72.500 Y50.382 Z-100.330 B-1.054 C-450.000 U6.075 F300
G1 X72.500 Y51.464 Z-98.799 B-1.054 C-450.000 U6.113 F300
G1 X72.500 Y52.547 Z-97.268 B-1.054 C-450.000 U6.150 F300
G1 X72.500 Y53.629 Z-95.737 B-1.054 C-450.000 U6.188 F300
G1 X72.500 Y54.712 Z-94.207 B-1.054 C-450.000 U6.225 F300
G1 X72.500 Y55.794 Z-92.676 B-1.054 C-450.000 U6.263 F300
G1 X72.500 Y56.877 Z-91.145 B-1.054 C-450.000 U6.300 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U3.300 F240
; --- edge 12/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-450.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X57.500 Y48.217 Z-103.392 B-1.054 C-450.000 F1200
; pressure preload before print pass
G1 U6.300 F120
G4 P700
G1 X57.500 Y49.299 Z-101.861 B-1.054 C-450.000 U6.338 F300
G1 X57.500 Y50.382 Z-100.330 B-1.054 C-450.000 U6.375 F300
G1 X57.500 Y51.464 Z-98.799 B-1.054 C-450.000 U6.413 F300
G1 X57.500 Y52.547 Z-97.268 B-1.054 C-450.000 U6.450 F300
G1 X57.500 Y53.629 Z-95.737 B-1.054 C-450.000 U6.488 F300
G1 X57.500 Y54.712 Z-94.207 B-1.054 C-450.000 U6.525 F300
G1 X57.500 Y55.794 Z-92.676 B-1.054 C-450.000 U6.563 F300
G1 X57.500 Y56.877 Z-91.145 B-1.054 C-450.000 U6.600 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U3.600 F240
; --- edge 13/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-330.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X62.794 Y57.387 Z-103.392 B-1.054 C-330.000 F1200
; pressure preload before print pass
G1 U6.600 F120
G4 P700
G1 X61.857 Y56.846 Z-101.861 B-1.054 C-330.000 U6.638 F300
G1 X60.919 Y56.304 Z-100.330 B-1.054 C-330.000 U6.675 F300
G1 X59.982 Y55.763 Z-98.799 B-1.054 C-330.000 U6.713 F300
G1 X59.044 Y55.222 Z-97.268 B-1.054 C-330.000 U6.750 F300
G1 X58.107 Y54.681 Z-95.737 B-1.054 C-330.000 U6.788 F300
G1 X57.169 Y54.139 Z-94.207 B-1.054 C-330.000 U6.825 F300
G1 X56.232 Y53.598 Z-92.676 B-1.054 C-330.000 U6.863 F300
G1 X55.294 Y53.057 Z-91.145 B-1.054 C-330.000 U6.900 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U3.900 F240
; --- edge 14/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-210.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X67.206 Y57.387 Z-103.392 B-1.054 C-210.000 F1200
; pressure preload before print pass
G1 U6.900 F120
G4 P700
G1 X68.143 Y56.846 Z-101.861 B-1.054 C-210.000 U6.938 F300
G1 X69.081 Y56.304 Z-100.330 B-1.054 C-210.000 U6.975 F300
G1 X70.018 Y55.763 Z-98.799 B-1.054 C-210.000 U7.013 F300
G1 X70.956 Y55.222 Z-97.268 B-1.054 C-210.000 U7.050 F300
G1 X71.893 Y54.681 Z-95.737 B-1.054 C-210.000 U7.088 F300
G1 X72.831 Y54.139 Z-94.207 B-1.054 C-210.000 U7.125 F300
G1 X73.768 Y53.598 Z-92.676 B-1.054 C-210.000 U7.163 F300
G1 X74.706 Y53.057 Z-91.145 B-1.054 C-210.000 U7.200 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U4.200 F240
; --- edge 15/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-90.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X65.000 Y61.207 Z-103.392 B-1.054 C-90.000 F1200
; pressure preload before print pass
G1 U7.200 F120
G4 P700
G1 X65.000 Y62.290 Z-101.861 B-1.054 C-90.000 U7.237 F300
G1 X65.000 Y63.372 Z-100.330 B-1.054 C-90.000 U7.275 F300
G1 X65.000 Y64.455 Z-98.799 B-1.054 C-90.000 U7.312 F300
G1 X65.000 Y65.537 Z-97.268 B-1.054 C-90.000 U7.350 F300
G1 X65.000 Y66.620 Z-95.737 B-1.054 C-90.000 U7.387 F300
G1 X65.000 Y67.702 Z-94.207 B-1.054 C-90.000 U7.425 F300
G1 X65.000 Y68.785 Z-92.676 B-1.054 C-90.000 U7.462 F300
G1 X65.000 Y69.867 Z-91.145 B-1.054 C-90.000 U7.500 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U4.500 F240
; --- edge 16/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-240.000, head_lead=-1.229 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X64.385 Y77.045 Z-97.449 B-2.521 C-240.000 F1200
; pressure preload before print pass
G1 U7.500 F120
G4 P700
G1 X65.323 Y75.422 Z-97.449 B-2.521 C-240.000 U7.537 F300
G1 X66.260 Y73.798 Z-97.449 B-2.521 C-240.000 U7.575 F300
G1 X67.198 Y72.174 Z-97.449 B-2.521 C-240.000 U7.612 F300
G1 X68.135 Y70.550 Z-97.449 B-2.521 C-240.000 U7.650 F300
G1 X69.073 Y68.926 Z-97.449 B-2.521 C-240.000 U7.687 F300
G1 X70.010 Y67.303 Z-97.449 B-2.521 C-240.000 U7.725 F300
G1 X70.948 Y65.679 Z-97.449 B-2.521 C-240.000 U7.762 F300
G1 X71.885 Y64.055 Z-97.449 B-2.521 C-240.000 U7.800 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 17/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-240.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X71.885 Y64.055 Z-97.449 B-2.521 C-240.000 F1200
G1 X72.823 Y62.431 Z-97.449 B-2.521 C-240.000 U7.837 F300
G1 X73.760 Y60.807 Z-97.449 B-2.521 C-240.000 U7.875 F300
G1 X74.698 Y59.184 Z-97.449 B-2.521 C-240.000 U7.912 F300
G1 X75.635 Y57.560 Z-97.449 B-2.521 C-240.000 U7.950 F300
G1 X76.573 Y55.936 Z-97.449 B-2.521 C-240.000 U7.987 F300
G1 X77.510 Y54.312 Z-97.449 B-2.521 C-240.000 U8.025 F300
G1 X78.448 Y52.688 Z-97.449 B-2.521 C-240.000 U8.062 F300
G1 X79.385 Y51.065 Z-97.449 B-2.521 C-240.000 U8.100 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 18/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-360.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X81.229 Y50.000 Z-97.449 B-2.521 C-360.000 F1200
G1 X79.354 Y50.000 Z-97.449 B-2.521 C-360.000 U8.137 F300
G1 X77.479 Y50.000 Z-97.449 B-2.521 C-360.000 U8.175 F300
G1 X75.604 Y50.000 Z-97.449 B-2.521 C-360.000 U8.212 F300
G1 X73.729 Y50.000 Z-97.449 B-2.521 C-360.000 U8.250 F300
G1 X71.854 Y50.000 Z-97.449 B-2.521 C-360.000 U8.287 F300
G1 X69.979 Y50.000 Z-97.449 B-2.521 C-360.000 U8.325 F300
G1 X68.104 Y50.000 Z-97.449 B-2.521 C-360.000 U8.362 F300
G1 X66.229 Y50.000 Z-97.449 B-2.521 C-360.000 U8.400 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 19/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-480.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X64.385 Y48.935 Z-97.449 B-2.521 C-480.000 F1200
G1 X65.323 Y50.559 Z-97.449 B-2.521 C-480.000 U8.437 F300
G1 X66.260 Y52.183 Z-97.449 B-2.521 C-480.000 U8.475 F300
G1 X67.198 Y53.807 Z-97.449 B-2.521 C-480.000 U8.512 F300
G1 X68.135 Y55.431 Z-97.449 B-2.521 C-480.000 U8.550 F300
G1 X69.073 Y57.054 Z-97.449 B-2.521 C-480.000 U8.587 F300
G1 X70.010 Y58.678 Z-97.449 B-2.521 C-480.000 U8.625 F300
G1 X70.948 Y60.302 Z-97.449 B-2.521 C-480.000 U8.662 F300
G1 X71.885 Y61.926 Z-97.449 B-2.521 C-480.000 U8.700 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 20/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-360.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X73.729 Y62.990 Z-97.449 B-2.521 C-360.000 F1200
G1 X71.854 Y62.990 Z-97.449 B-2.521 C-360.000 U8.737 F300
G1 X69.979 Y62.990 Z-97.449 B-2.521 C-360.000 U8.775 F300
G1 X68.104 Y62.990 Z-97.449 B-2.521 C-360.000 U8.812 F300
G1 X66.229 Y62.990 Z-97.449 B-2.521 C-360.000 U8.850 F300
G1 X64.354 Y62.990 Z-97.449 B-2.521 C-360.000 U8.887 F300
G1 X62.479 Y62.990 Z-97.449 B-2.521 C-360.000 U8.925 F300
G1 X60.604 Y62.990 Z-97.449 B-2.521 C-360.000 U8.962 F300
G1 X58.729 Y62.990 Z-97.449 B-2.521 C-360.000 U9.000 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 21/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-480.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X56.885 Y61.926 Z-97.449 B-2.521 C-480.000 F1200
G1 X57.823 Y63.550 Z-97.449 B-2.521 C-480.000 U9.037 F300
G1 X58.760 Y65.173 Z-97.449 B-2.521 C-480.000 U9.075 F300
G1 X59.698 Y66.797 Z-97.449 B-2.521 C-480.000 U9.112 F300
G1 X60.635 Y68.421 Z-97.449 B-2.521 C-480.000 U9.150 F300
G1 X61.573 Y70.045 Z-97.449 B-2.521 C-480.000 U9.187 F300
G1 X62.510 Y71.669 Z-97.449 B-2.521 C-480.000 U9.225 F300
G1 X63.448 Y73.292 Z-97.449 B-2.521 C-480.000 U9.262 F300
G1 X64.385 Y74.916 Z-97.449 B-2.521 C-480.000 U9.300 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U6.300 F240
; --- edge 22/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-600.000, head_lead=-1.229 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X56.885 Y64.055 Z-97.449 B-2.521 C-600.000 F1200
; pressure preload before print pass
G1 U9.300 F120
G4 P700
G1 X57.823 Y62.431 Z-97.449 B-2.521 C-600.000 U9.337 F300
G1 X58.760 Y60.807 Z-97.449 B-2.521 C-600.000 U9.375 F300
G1 X59.698 Y59.184 Z-97.449 B-2.521 C-600.000 U9.412 F300
G1 X60.635 Y57.560 Z-97.449 B-2.521 C-600.000 U9.450 F300
G1 X61.573 Y55.936 Z-97.449 B-2.521 C-600.000 U9.487 F300
G1 X62.510 Y54.312 Z-97.449 B-2.521 C-600.000 U9.525 F300
G1 X63.448 Y52.688 Z-97.449 B-2.521 C-600.000 U9.562 F300
G1 X64.385 Y51.065 Z-97.449 B-2.521 C-600.000 U9.600 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 23/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-720.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X66.229 Y50.000 Z-97.449 B-2.521 C-720.000 F1200
G1 X64.354 Y50.000 Z-97.449 B-2.521 C-720.000 U9.637 F300
G1 X62.479 Y50.000 Z-97.449 B-2.521 C-720.000 U9.675 F300
G1 X60.604 Y50.000 Z-97.449 B-2.521 C-720.000 U9.712 F300
G1 X58.729 Y50.000 Z-97.449 B-2.521 C-720.000 U9.750 F300
G1 X56.854 Y50.000 Z-97.449 B-2.521 C-720.000 U9.787 F300
G1 X54.979 Y50.000 Z-97.449 B-2.521 C-720.000 U9.825 F300
G1 X53.104 Y50.000 Z-97.449 B-2.521 C-720.000 U9.862 F300
G1 X51.229 Y50.000 Z-97.449 B-2.521 C-720.000 U9.900 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 24/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-840.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X49.385 Y48.935 Z-97.449 B-2.521 C-840.000 F1200
G1 X50.323 Y50.559 Z-97.449 B-2.521 C-840.000 U9.937 F300
G1 X51.260 Y52.183 Z-97.449 B-2.521 C-840.000 U9.975 F300
G1 X52.198 Y53.807 Z-97.449 B-2.521 C-840.000 U10.012 F300
G1 X53.135 Y55.431 Z-97.449 B-2.521 C-840.000 U10.050 F300
G1 X54.073 Y57.054 Z-97.449 B-2.521 C-840.000 U10.087 F300
G1 X55.010 Y58.678 Z-97.449 B-2.521 C-840.000 U10.125 F300
G1 X55.948 Y60.302 Z-97.449 B-2.521 C-840.000 U10.162 F300
G1 X56.885 Y61.926 Z-97.449 B-2.521 C-840.000 U10.200 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U7.200 F240
; --- edge 25/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-870.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X52.206 Y59.934 Z-91.145 B-1.054 C-870.000 F1200
; pressure preload before print pass
G1 U10.200 F120
G4 P700
G1 X53.143 Y60.475 Z-89.614 B-1.054 C-870.000 U10.237 F300
G1 X54.081 Y61.016 Z-88.083 B-1.054 C-870.000 U10.275 F300
G1 X55.018 Y61.557 Z-86.552 B-1.054 C-870.000 U10.312 F300
G1 X55.956 Y62.099 Z-85.021 B-1.054 C-870.000 U10.350 F300
G1 X56.893 Y62.640 Z-83.490 B-1.054 C-870.000 U10.387 F300
G1 X57.831 Y63.181 Z-81.959 B-1.054 C-870.000 U10.425 F300
G1 X58.768 Y63.723 Z-80.428 B-1.054 C-870.000 U10.462 F300
G1 X59.706 Y64.264 Z-78.897 B-1.054 C-870.000 U10.500 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U7.500 F240
; --- edge 26/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-750.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X77.794 Y59.934 Z-91.145 B-1.054 C-750.000 F1200
; pressure preload before print pass
G1 U10.500 F120
G4 P700
G1 X76.857 Y60.475 Z-89.614 B-1.054 C-750.000 U10.537 F300
G1 X75.919 Y61.016 Z-88.083 B-1.054 C-750.000 U10.575 F300
G1 X74.982 Y61.557 Z-86.552 B-1.054 C-750.000 U10.612 F300
G1 X74.044 Y62.099 Z-85.021 B-1.054 C-750.000 U10.650 F300
G1 X73.107 Y62.640 Z-83.490 B-1.054 C-750.000 U10.687 F300
G1 X72.169 Y63.181 Z-81.959 B-1.054 C-750.000 U10.725 F300
G1 X71.232 Y63.723 Z-80.428 B-1.054 C-750.000 U10.762 F300
G1 X70.294 Y64.264 Z-78.897 B-1.054 C-750.000 U10.800 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U7.800 F240
; --- edge 27/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-750.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X70.294 Y46.943 Z-91.145 B-1.054 C-750.000 F1200
; pressure preload before print pass
G1 U10.800 F120
G4 P700
G1 X69.357 Y47.485 Z-89.614 B-1.054 C-750.000 U10.837 F300
G1 X68.419 Y48.026 Z-88.083 B-1.054 C-750.000 U10.875 F300
G1 X67.482 Y48.567 Z-86.552 B-1.054 C-750.000 U10.912 F300
G1 X66.544 Y49.108 Z-85.021 B-1.054 C-750.000 U10.950 F300
G1 X65.607 Y49.650 Z-83.490 B-1.054 C-750.000 U10.987 F300
G1 X64.669 Y50.191 Z-81.959 B-1.054 C-750.000 U11.025 F300
G1 X63.732 Y50.732 Z-80.428 B-1.054 C-750.000 U11.062 F300
G1 X62.794 Y51.273 Z-78.897 B-1.054 C-750.000 U11.100 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U8.100 F240
; --- edge 28/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-870.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X59.706 Y46.943 Z-91.145 B-1.054 C-870.000 F1200
; pressure preload before print pass
G1 U11.100 F120
G4 P700
G1 X60.643 Y47.485 Z-89.614 B-1.054 C-870.000 U11.137 F300
G1 X61.581 Y48.026 Z-88.083 B-1.054 C-870.000 U11.175 F300
G1 X62.518 Y48.567 Z-86.552 B-1.054 C-870.000 U11.212 F300
G1 X63.456 Y49.108 Z-85.021 B-1.054 C-870.000 U11.250 F300
G1 X64.393 Y49.650 Z-83.490 B-1.054 C-870.000 U11.287 F300
G1 X65.331 Y50.191 Z-81.959 B-1.054 C-870.000 U11.325 F300
G1 X66.268 Y50.732 Z-80.428 B-1.054 C-870.000 U11.362 F300
G1 X67.206 Y51.273 Z-78.897 B-1.054 C-870.000 U11.400 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U8.400 F240
; --- edge 29/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-990.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X72.500 Y69.104 Z-91.145 B-1.054 C-990.000 F1200
; pressure preload before print pass
G1 U11.400 F120
G4 P700
G1 X72.500 Y68.021 Z-89.614 B-1.054 C-990.000 U11.437 F300
G1 X72.500 Y66.939 Z-88.083 B-1.054 C-990.000 U11.475 F300
G1 X72.500 Y65.856 Z-86.552 B-1.054 C-990.000 U11.512 F300
G1 X72.500 Y64.774 Z-85.021 B-1.054 C-990.000 U11.550 F300
G1 X72.500 Y63.691 Z-83.490 B-1.054 C-990.000 U11.587 F300
G1 X72.500 Y62.609 Z-81.959 B-1.054 C-990.000 U11.625 F300
G1 X72.500 Y61.526 Z-80.428 B-1.054 C-990.000 U11.662 F300
G1 X72.500 Y60.444 Z-78.897 B-1.054 C-990.000 U11.700 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U8.700 F240
; --- edge 30/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-990.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X57.500 Y69.104 Z-91.145 B-1.054 C-990.000 F1200
; pressure preload before print pass
G1 U11.700 F120
G4 P700
G1 X57.500 Y68.021 Z-89.614 B-1.054 C-990.000 U11.737 F300
G1 X57.500 Y66.939 Z-88.083 B-1.054 C-990.000 U11.775 F300
G1 X57.500 Y65.856 Z-86.552 B-1.054 C-990.000 U11.812 F300
G1 X57.500 Y64.774 Z-85.021 B-1.054 C-990.000 U11.850 F300
G1 X57.500 Y63.691 Z-83.490 B-1.054 C-990.000 U11.887 F300
G1 X57.500 Y62.609 Z-81.959 B-1.054 C-990.000 U11.925 F300
G1 X57.500 Y61.526 Z-80.428 B-1.054 C-990.000 U11.962 F300
G1 X57.500 Y60.444 Z-78.897 B-1.054 C-990.000 U12.000 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U9.000 F240
; --- edge 31/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-1110.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X85.294 Y46.943 Z-91.145 B-1.054 C-1110.000 F1200
; pressure preload before print pass
G1 U12.000 F120
G4 P700
G1 X84.357 Y47.485 Z-89.614 B-1.054 C-1110.000 U12.037 F300
G1 X83.419 Y48.026 Z-88.083 B-1.054 C-1110.000 U12.075 F300
G1 X82.482 Y48.567 Z-86.552 B-1.054 C-1110.000 U12.112 F300
G1 X81.544 Y49.108 Z-85.021 B-1.054 C-1110.000 U12.150 F300
G1 X80.607 Y49.650 Z-83.490 B-1.054 C-1110.000 U12.187 F300
G1 X79.669 Y50.191 Z-81.959 B-1.054 C-1110.000 U12.225 F300
G1 X78.732 Y50.732 Z-80.428 B-1.054 C-1110.000 U12.262 F300
G1 X77.794 Y51.273 Z-78.897 B-1.054 C-1110.000 U12.300 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U9.300 F240
; --- edge 32/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-1230.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X44.706 Y46.943 Z-91.145 B-1.054 C-1230.000 F1200
; pressure preload before print pass
G1 U12.300 F120
G4 P700
G1 X45.643 Y47.485 Z-89.614 B-1.054 C-1230.000 U12.337 F300
G1 X46.581 Y48.026 Z-88.083 B-1.054 C-1230.000 U12.375 F300
G1 X47.518 Y48.567 Z-86.552 B-1.054 C-1230.000 U12.412 F300
G1 X48.456 Y49.108 Z-85.021 B-1.054 C-1230.000 U12.450 F300
G1 X49.393 Y49.650 Z-83.490 B-1.054 C-1230.000 U12.487 F300
G1 X50.331 Y50.191 Z-81.959 B-1.054 C-1230.000 U12.525 F300
G1 X51.268 Y50.732 Z-80.428 B-1.054 C-1230.000 U12.562 F300
G1 X52.206 Y51.273 Z-78.897 B-1.054 C-1230.000 U12.600 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U9.600 F240
; --- edge 33/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-1350.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X65.000 Y82.094 Z-91.145 B-1.054 C-1350.000 F1200
; pressure preload before print pass
G1 U12.600 F120
G4 P700
G1 X65.000 Y81.012 Z-89.614 B-1.054 C-1350.000 U12.637 F300
G1 X65.000 Y79.929 Z-88.083 B-1.054 C-1350.000 U12.675 F300
G1 X65.000 Y78.847 Z-86.552 B-1.054 C-1350.000 U12.712 F300
G1 X65.000 Y77.764 Z-85.021 B-1.054 C-1350.000 U12.750 F300
G1 X65.000 Y76.682 Z-83.490 B-1.054 C-1350.000 U12.787 F300
G1 X65.000 Y75.599 Z-81.959 B-1.054 C-1350.000 U12.825 F300
G1 X65.000 Y74.516 Z-80.428 B-1.054 C-1350.000 U12.862 F300
G1 X65.000 Y73.434 Z-78.897 B-1.054 C-1350.000 U12.900 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U9.900 F240
; --- edge 34/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-1320.000, head_lead=-1.229 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X64.385 Y68.385 Z-85.202 B-2.521 C-1320.000 F1200
; pressure preload before print pass
G1 U12.900 F120
G4 P700
G1 X65.323 Y66.761 Z-85.202 B-2.521 C-1320.000 U12.937 F300
G1 X66.260 Y65.138 Z-85.202 B-2.521 C-1320.000 U12.975 F300
G1 X67.198 Y63.514 Z-85.202 B-2.521 C-1320.000 U13.012 F300
G1 X68.135 Y61.890 Z-85.202 B-2.521 C-1320.000 U13.050 F300
G1 X69.073 Y60.266 Z-85.202 B-2.521 C-1320.000 U13.087 F300
G1 X70.010 Y58.642 Z-85.202 B-2.521 C-1320.000 U13.125 F300
G1 X70.948 Y57.019 Z-85.202 B-2.521 C-1320.000 U13.162 F300
G1 X71.885 Y55.395 Z-85.202 B-2.521 C-1320.000 U13.200 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 35/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-1440.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X73.729 Y54.330 Z-85.202 B-2.521 C-1440.000 F1200
G1 X71.854 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.237 F300
G1 X69.979 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.275 F300
G1 X68.104 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.312 F300
G1 X66.229 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.350 F300
G1 X64.354 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.387 F300
G1 X62.479 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.425 F300
G1 X60.604 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.462 F300
G1 X58.729 Y54.330 Z-85.202 B-2.521 C-1440.000 U13.500 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 36/39 ---
; len=15.000 mm, angle_error=0.057 deg, B=-2.521, C=-1560.000, head_lead=-1.229 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X56.885 Y53.265 Z-85.202 B-2.521 C-1560.000 F1200
G1 X57.823 Y54.889 Z-85.202 B-2.521 C-1560.000 U13.537 F300
G1 X58.760 Y56.513 Z-85.202 B-2.521 C-1560.000 U13.575 F300
G1 X59.698 Y58.137 Z-85.202 B-2.521 C-1560.000 U13.612 F300
G1 X60.635 Y59.761 Z-85.202 B-2.521 C-1560.000 U13.650 F300
G1 X61.573 Y61.384 Z-85.202 B-2.521 C-1560.000 U13.687 F300
G1 X62.510 Y63.008 Z-85.202 B-2.521 C-1560.000 U13.725 F300
G1 X63.448 Y64.632 Z-85.202 B-2.521 C-1560.000 U13.762 F300
G1 X64.385 Y66.256 Z-85.202 B-2.521 C-1560.000 U13.800 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U10.800 F240
; --- edge 37/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-1710.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X65.000 Y73.434 Z-78.897 B-1.054 C-1710.000 F1200
; pressure preload before print pass
G1 U13.800 F120
G4 P700
G1 X65.000 Y72.351 Z-77.366 B-1.054 C-1710.000 U13.837 F300
G1 X65.000 Y71.269 Z-75.835 B-1.054 C-1710.000 U13.875 F300
G1 X65.000 Y70.186 Z-74.304 B-1.054 C-1710.000 U13.912 F300
G1 X65.000 Y69.104 Z-72.773 B-1.054 C-1710.000 U13.950 F300
G1 X65.000 Y68.021 Z-71.243 B-1.054 C-1710.000 U13.987 F300
G1 X65.000 Y66.939 Z-69.712 B-1.054 C-1710.000 U14.025 F300
G1 X65.000 Y65.856 Z-68.181 B-1.054 C-1710.000 U14.062 F300
G1 X65.000 Y64.774 Z-66.650 B-1.054 C-1710.000 U14.100 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U11.100 F240
; --- edge 38/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-1830.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X77.794 Y51.273 Z-78.897 B-1.054 C-1830.000 F1200
; pressure preload before print pass
G1 U14.100 F120
G4 P700
G1 X76.857 Y51.815 Z-77.366 B-1.054 C-1830.000 U14.137 F300
G1 X75.919 Y52.356 Z-75.835 B-1.054 C-1830.000 U14.175 F300
G1 X74.982 Y52.897 Z-74.304 B-1.054 C-1830.000 U14.212 F300
G1 X74.044 Y53.438 Z-72.773 B-1.054 C-1830.000 U14.250 F300
G1 X73.107 Y53.980 Z-71.243 B-1.054 C-1830.000 U14.287 F300
G1 X72.169 Y54.521 Z-69.712 B-1.054 C-1830.000 U14.325 F300
G1 X71.232 Y55.062 Z-68.181 B-1.054 C-1830.000 U14.362 F300
G1 X70.294 Y55.604 Z-66.650 B-1.054 C-1830.000 U14.400 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U11.400 F240
; --- edge 39/39 ---
; len=15.000 mm, angle_error=0.044 deg, B=-1.054, C=-1950.000, head_lead=-4.464 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X52.206 Y51.273 Z-78.897 B-1.054 C-1950.000 F1200
; pressure preload before print pass
G1 U14.400 F120
G4 P700
G1 X53.143 Y51.815 Z-77.366 B-1.054 C-1950.000 U14.437 F300
G1 X54.081 Y52.356 Z-75.835 B-1.054 C-1950.000 U14.475 F300
G1 X55.018 Y52.897 Z-74.304 B-1.054 C-1950.000 U14.512 F300
G1 X55.956 Y53.438 Z-72.773 B-1.054 C-1950.000 U14.550 F300
G1 X56.893 Y53.980 Z-71.243 B-1.054 C-1950.000 U14.587 F300
G1 X57.831 Y54.521 Z-69.712 B-1.054 C-1950.000 U14.625 F300
G1 X58.768 Y55.062 Z-68.181 B-1.054 C-1950.000 U14.662 F300
G1 X59.706 Y55.604 Z-66.650 B-1.054 C-1950.000 U14.700 F300
; end-of-pass dwell for node formation / liquid flow
G4 P700
; pressure release before travel
G1 U11.700 F240
; safe end move: raise to safe Z, move XY, then dive to end Z
G1 Z0.000 B0.000 C0.000 F1200
G1 X60.000 Y40.000 B0.000 C0.000 F1200
G1 Z-30.000 B0.000 C0.000 F1200
; emitted edges = 39
; bbox warning count = 0
; --- end ---
