; generated by tetrahedral_truss_tip_priority_tangent_soft.py
; strategy: exact tip position (hard) + tangent/nozzle angle alignment (soft)
; user tip-angle convention: angle measured FROM VERTICAL (horizontal line ~90 deg)
; head-front preference: choose edge direction so head/stage leads deposition point when possible
; build order heuristic: bottom-center-first, bottom-up, center-out
; geometry: double tetrahedron (mirrored along base plane)
; PHYSICAL tip kinematics uses local [r(B), y_off(B)] rotated by C; attack azimuth remap is tangency-only
; model assumptions:
;   physical tip_offset(B,C): [x,y]=Rot(C)@[r(B), y_off(B)], z=z(B)
;   nozzle attack dir(B,C) = [sin(a(B)) cos(theta_attack), sin(a(B)) sin(theta_attack), cos(a(B))]
;   theta_attack = C + +180.000 deg
;   a(B) = (+1.000) * tip_angle_poly(B) + +0.000 deg
; offplane_y_equation (calibration): y_offplane_mm = 1.082018*b + 4.553792
; offplane_y_r_squared: 0.952224
; offplane sign convention applied: -1.0
; axes: X->X, Y->Y, Z->Z, B->B, C->C, U->U
; edges planned = 39 (all edges extruded exactly once)
; total print length ~ 546.000 mm
; total tip travel  ~ 390.641 mm
; tangent angle error [min/mean/max] = 0.068 / 0.078 / 0.094 deg
; head-lead [min/mean/max] mm = -10.380 / -8.391 / -5.209
; head-front ok / violations = 0 / 39
; B used range = [-3.459, -2.094]
; C used range = [-870.000, 510.000]
; X gantry range used = [54.353, 105.935]
; Y gantry range used = [10.426, 57.864]
; Z gantry range used = [-155.947, -110.223]
; virtual bbox (enforced during print/travel): X[0.000, 160.000] Y[0.000, 160.000] Z[-170.000, -10.000]
; startup safe approach Z = 0.000
; start pose (stage) = [65.000, 20.000, 0.000, 0.000, 0.000]
; end pose (stage)   = [65.000, 20.000, 0.000, 0.000, 0.000]
; bottom-center start (tip-space heuristic origin) = [79.000, 28.083, -152.862]
; extrusion_per_mm = 0.008000 U/mm-path (coordinated with print feed)
; pressure_offset_mm = 5.000 U mm
; pressure advance/retract feeds = 120.0/240.0 mm/min on U
; preflow_dwell_ms = 200   node_dwell_ms = 200
G90
M82
G92 U0
; safe startup approach: Z first, then XY, then dive to start Z
G1 Z0.000 B0.000 C0.000 F1200
G1 X65.000 Y20.000 B0.000 C0.000 F1200
G1 Z0.000 B0.000 C0.000 F1200
; --- edge 1/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=270.000, head_lead=-10.380 mm, head_front_ok=0
; startup move to first strut start (bottom-center-first ordering)
G1 X81.288 Y14.468 Z-155.947 B-2.094 C270.000 F1200
; pressure preload before print pass
G1 U5.000 F120
G4 P200
G1 X81.288 Y15.478 Z-154.518 B-2.094 C270.000 U5.014 F300
G1 X81.288 Y16.488 Z-153.090 B-2.094 C270.000 U5.028 F300
G1 X81.288 Y17.499 Z-151.661 B-2.094 C270.000 U5.042 F300
G1 X81.288 Y18.509 Z-150.232 B-2.094 C270.000 U5.056 F300
G1 X81.288 Y19.520 Z-148.803 B-2.094 C270.000 U5.070 F300
G1 X81.288 Y20.530 Z-147.374 B-2.094 C270.000 U5.084 F300
G1 X81.288 Y21.540 Z-145.945 B-2.094 C270.000 U5.098 F300
G1 X81.288 Y22.551 Z-144.516 B-2.094 C270.000 U5.112 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U0.112 F240
; --- edge 2/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=390.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X89.647 Y36.872 Z-155.947 B-2.094 C390.000 F1200
; pressure preload before print pass
G1 U5.112 F120
G4 P200
G1 X88.772 Y36.366 Z-154.518 B-2.094 C390.000 U5.126 F300
G1 X87.897 Y35.861 Z-153.090 B-2.094 C390.000 U5.140 F300
G1 X87.022 Y35.356 Z-151.661 B-2.094 C390.000 U5.154 F300
G1 X86.147 Y34.851 Z-150.232 B-2.094 C390.000 U5.168 F300
G1 X85.272 Y34.346 Z-148.803 B-2.094 C390.000 U5.182 F300
G1 X84.397 Y33.840 Z-147.374 B-2.094 C390.000 U5.196 F300
G1 X83.522 Y33.335 Z-145.945 B-2.094 C390.000 U5.210 F300
G1 X82.647 Y32.830 Z-144.516 B-2.094 C390.000 U5.224 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U0.224 F240
; --- edge 3/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=510.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X66.065 Y32.909 Z-155.947 B-2.094 C510.000 F1200
; pressure preload before print pass
G1 U5.224 F120
G4 P200
G1 X66.940 Y32.404 Z-154.518 B-2.094 C510.000 U5.238 F300
G1 X67.815 Y31.899 Z-153.090 B-2.094 C510.000 U5.252 F300
G1 X68.690 Y31.394 Z-151.661 B-2.094 C510.000 U5.266 F300
G1 X69.565 Y30.889 Z-150.232 B-2.094 C510.000 U5.280 F300
G1 X70.440 Y30.383 Z-148.803 B-2.094 C510.000 U5.294 F300
G1 X71.315 Y29.878 Z-147.374 B-2.094 C510.000 U5.308 F300
G1 X72.190 Y29.373 Z-145.945 B-2.094 C510.000 U5.322 F300
G1 X73.065 Y28.868 Z-144.516 B-2.094 C510.000 U5.336 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U0.336 F240
; --- edge 4/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=360.000, head_lead=-5.209 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X91.209 Y24.852 Z-154.796 B-3.459 C360.000 F1200
; pressure preload before print pass
G1 U5.336 F120
G4 P200
G1 X89.459 Y24.852 Z-154.796 B-3.459 C360.000 U5.350 F300
G1 X87.709 Y24.852 Z-154.796 B-3.459 C360.000 U5.364 F300
G1 X85.959 Y24.852 Z-154.796 B-3.459 C360.000 U5.378 F300
G1 X84.209 Y24.852 Z-154.796 B-3.459 C360.000 U5.392 F300
G1 X82.459 Y24.852 Z-154.796 B-3.459 C360.000 U5.406 F300
G1 X80.709 Y24.852 Z-154.796 B-3.459 C360.000 U5.420 F300
G1 X78.959 Y24.852 Z-154.796 B-3.459 C360.000 U5.434 F300
G1 X77.209 Y24.852 Z-154.796 B-3.459 C360.000 U5.448 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 5/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=240.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X70.098 Y19.125 Z-154.796 B-3.459 C240.000 F1200
G1 X70.973 Y20.641 Z-154.796 B-3.459 C240.000 U5.462 F300
G1 X71.848 Y22.156 Z-154.796 B-3.459 C240.000 U5.476 F300
G1 X72.723 Y23.672 Z-154.796 B-3.459 C240.000 U5.490 F300
G1 X73.598 Y25.188 Z-154.796 B-3.459 C240.000 U5.504 F300
G1 X74.473 Y26.703 Z-154.796 B-3.459 C240.000 U5.518 F300
G1 X75.348 Y28.219 Z-154.796 B-3.459 C240.000 U5.532 F300
G1 X76.223 Y29.734 Z-154.796 B-3.459 C240.000 U5.546 F300
G1 X77.098 Y31.250 Z-154.796 B-3.459 C240.000 U5.560 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 6/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=120.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X75.694 Y40.271 Z-154.796 B-3.459 C120.000 F1200
G1 X76.569 Y38.756 Z-154.796 B-3.459 C120.000 U5.574 F300
G1 X77.444 Y37.240 Z-154.796 B-3.459 C120.000 U5.588 F300
G1 X78.319 Y35.725 Z-154.796 B-3.459 C120.000 U5.602 F300
G1 X79.194 Y34.209 Z-154.796 B-3.459 C120.000 U5.616 F300
G1 X80.069 Y32.694 Z-154.796 B-3.459 C120.000 U5.630 F300
G1 X80.944 Y31.178 Z-154.796 B-3.459 C120.000 U5.644 F300
G1 X81.819 Y29.662 Z-154.796 B-3.459 C120.000 U5.658 F300
G1 X82.694 Y28.147 Z-154.796 B-3.459 C120.000 U5.672 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U0.672 F240
; --- edge 7/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=150.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X66.065 Y40.992 Z-144.516 B-2.094 C150.000 F1200
; pressure preload before print pass
G1 U5.672 F120
G4 P200
G1 X66.940 Y40.487 Z-143.087 B-2.094 C150.000 U5.686 F300
G1 X67.815 Y39.982 Z-141.659 B-2.094 C150.000 U5.700 F300
G1 X68.690 Y39.477 Z-140.230 B-2.094 C150.000 U5.714 F300
G1 X69.565 Y38.972 Z-138.801 B-2.094 C150.000 U5.728 F300
G1 X70.440 Y38.466 Z-137.372 B-2.094 C150.000 U5.742 F300
G1 X71.315 Y37.961 Z-135.943 B-2.094 C150.000 U5.756 F300
G1 X72.190 Y37.456 Z-134.514 B-2.094 C150.000 U5.770 F300
G1 X73.065 Y36.951 Z-133.085 B-2.094 C150.000 U5.784 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U0.784 F240
; --- edge 8/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=30.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X89.647 Y44.954 Z-144.516 B-2.094 C30.000 F1200
; pressure preload before print pass
G1 U5.784 F120
G4 P200
G1 X88.772 Y44.449 Z-143.087 B-2.094 C30.000 U5.798 F300
G1 X87.897 Y43.944 Z-141.659 B-2.094 C30.000 U5.812 F300
G1 X87.022 Y43.439 Z-140.230 B-2.094 C30.000 U5.826 F300
G1 X86.147 Y42.934 Z-138.801 B-2.094 C30.000 U5.840 F300
G1 X85.272 Y42.429 Z-137.372 B-2.094 C30.000 U5.854 F300
G1 X84.397 Y41.923 Z-135.943 B-2.094 C30.000 U5.868 F300
G1 X83.522 Y41.418 Z-134.514 B-2.094 C30.000 U5.882 F300
G1 X82.647 Y40.913 Z-133.085 B-2.094 C30.000 U5.896 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U0.896 F240
; --- edge 9/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=150.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X59.065 Y28.868 Z-144.516 B-2.094 C150.000 F1200
; pressure preload before print pass
G1 U5.896 F120
G4 P200
G1 X59.940 Y28.363 Z-143.087 B-2.094 C150.000 U5.910 F300
G1 X60.815 Y27.858 Z-141.659 B-2.094 C150.000 U5.924 F300
G1 X61.690 Y27.352 Z-140.230 B-2.094 C150.000 U5.938 F300
G1 X62.565 Y26.847 Z-138.801 B-2.094 C150.000 U5.952 F300
G1 X63.440 Y26.342 Z-137.372 B-2.094 C150.000 U5.966 F300
G1 X64.315 Y25.837 Z-135.943 B-2.094 C150.000 U5.980 F300
G1 X65.190 Y25.332 Z-134.514 B-2.094 C150.000 U5.994 F300
G1 X66.065 Y24.826 Z-133.085 B-2.094 C150.000 U6.008 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U1.008 F240
; --- edge 10/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=30.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X96.647 Y32.830 Z-144.516 B-2.094 C30.000 F1200
; pressure preload before print pass
G1 U6.008 F120
G4 P200
G1 X95.772 Y32.325 Z-143.087 B-2.094 C30.000 U6.022 F300
G1 X94.897 Y31.820 Z-141.659 B-2.094 C30.000 U6.036 F300
G1 X94.022 Y31.315 Z-140.230 B-2.094 C30.000 U6.050 F300
G1 X93.147 Y30.809 Z-138.801 B-2.094 C30.000 U6.064 F300
G1 X92.272 Y30.304 Z-137.372 B-2.094 C30.000 U6.078 F300
G1 X91.397 Y29.799 Z-135.943 B-2.094 C30.000 U6.092 F300
G1 X90.522 Y29.294 Z-134.514 B-2.094 C30.000 U6.106 F300
G1 X89.647 Y28.789 Z-133.085 B-2.094 C30.000 U6.120 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U1.120 F240
; --- edge 11/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-90.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X88.288 Y10.426 Z-144.516 B-2.094 C-90.000 F1200
; pressure preload before print pass
G1 U6.120 F120
G4 P200
G1 X88.288 Y11.437 Z-143.087 B-2.094 C-90.000 U6.134 F300
G1 X88.288 Y12.447 Z-141.659 B-2.094 C-90.000 U6.148 F300
G1 X88.288 Y13.457 Z-140.230 B-2.094 C-90.000 U6.162 F300
G1 X88.288 Y14.468 Z-138.801 B-2.094 C-90.000 U6.176 F300
G1 X88.288 Y15.478 Z-137.372 B-2.094 C-90.000 U6.190 F300
G1 X88.288 Y16.488 Z-135.943 B-2.094 C-90.000 U6.204 F300
G1 X88.288 Y17.499 Z-134.514 B-2.094 C-90.000 U6.218 F300
G1 X88.288 Y18.509 Z-133.085 B-2.094 C-90.000 U6.232 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U1.232 F240
; --- edge 12/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-90.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X74.288 Y10.426 Z-144.516 B-2.094 C-90.000 F1200
; pressure preload before print pass
G1 U6.232 F120
G4 P200
G1 X74.288 Y11.437 Z-143.087 B-2.094 C-90.000 U6.246 F300
G1 X74.288 Y12.447 Z-141.659 B-2.094 C-90.000 U6.260 F300
G1 X74.288 Y13.457 Z-140.230 B-2.094 C-90.000 U6.274 F300
G1 X74.288 Y14.468 Z-138.801 B-2.094 C-90.000 U6.288 F300
G1 X74.288 Y15.478 Z-137.372 B-2.094 C-90.000 U6.302 F300
G1 X74.288 Y16.488 Z-135.943 B-2.094 C-90.000 U6.316 F300
G1 X74.288 Y17.499 Z-134.514 B-2.094 C-90.000 U6.330 F300
G1 X74.288 Y18.509 Z-133.085 B-2.094 C-90.000 U6.344 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U1.344 F240
; --- edge 13/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-90.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X81.288 Y22.551 Z-144.516 B-2.094 C-90.000 F1200
; pressure preload before print pass
G1 U6.344 F120
G4 P200
G1 X81.288 Y23.561 Z-143.087 B-2.094 C-90.000 U6.358 F300
G1 X81.288 Y24.571 Z-141.659 B-2.094 C-90.000 U6.372 F300
G1 X81.288 Y25.582 Z-140.230 B-2.094 C-90.000 U6.386 F300
G1 X81.288 Y26.592 Z-138.801 B-2.094 C-90.000 U6.400 F300
G1 X81.288 Y27.602 Z-137.372 B-2.094 C-90.000 U6.414 F300
G1 X81.288 Y28.613 Z-135.943 B-2.094 C-90.000 U6.428 F300
G1 X81.288 Y29.623 Z-134.514 B-2.094 C-90.000 U6.442 F300
G1 X81.288 Y30.634 Z-133.085 B-2.094 C-90.000 U6.456 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U1.456 F240
; --- edge 14/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-210.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X73.065 Y28.868 Z-144.516 B-2.094 C-210.000 F1200
; pressure preload before print pass
G1 U6.456 F120
G4 P200
G1 X73.940 Y28.363 Z-143.087 B-2.094 C-210.000 U6.470 F300
G1 X74.815 Y27.858 Z-141.659 B-2.094 C-210.000 U6.484 F300
G1 X75.690 Y27.352 Z-140.230 B-2.094 C-210.000 U6.498 F300
G1 X76.565 Y26.847 Z-138.801 B-2.094 C-210.000 U6.512 F300
G1 X77.440 Y26.342 Z-137.372 B-2.094 C-210.000 U6.526 F300
G1 X78.315 Y25.837 Z-135.943 B-2.094 C-210.000 U6.540 F300
G1 X79.190 Y25.332 Z-134.514 B-2.094 C-210.000 U6.554 F300
G1 X80.065 Y24.826 Z-133.085 B-2.094 C-210.000 U6.568 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U1.568 F240
; --- edge 15/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-330.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X82.647 Y32.830 Z-144.516 B-2.094 C-330.000 F1200
; pressure preload before print pass
G1 U6.568 F120
G4 P200
G1 X81.772 Y32.325 Z-143.087 B-2.094 C-330.000 U6.582 F300
G1 X80.897 Y31.820 Z-141.659 B-2.094 C-330.000 U6.596 F300
G1 X80.022 Y31.315 Z-140.230 B-2.094 C-330.000 U6.610 F300
G1 X79.147 Y30.809 Z-138.801 B-2.094 C-330.000 U6.624 F300
G1 X78.272 Y30.304 Z-137.372 B-2.094 C-330.000 U6.638 F300
G1 X77.397 Y29.799 Z-135.943 B-2.094 C-330.000 U6.652 F300
G1 X76.522 Y29.294 Z-134.514 B-2.094 C-330.000 U6.666 F300
G1 X75.647 Y28.789 Z-133.085 B-2.094 C-330.000 U6.680 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U1.680 F240
; --- edge 16/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-480.000, head_lead=-5.209 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X63.098 Y15.084 Z-143.365 B-3.459 C-480.000 F1200
; pressure preload before print pass
G1 U6.680 F120
G4 P200
G1 X63.973 Y16.599 Z-143.365 B-3.459 C-480.000 U6.694 F300
G1 X64.848 Y18.115 Z-143.365 B-3.459 C-480.000 U6.708 F300
G1 X65.723 Y19.631 Z-143.365 B-3.459 C-480.000 U6.722 F300
G1 X66.598 Y21.146 Z-143.365 B-3.459 C-480.000 U6.736 F300
G1 X67.473 Y22.662 Z-143.365 B-3.459 C-480.000 U6.750 F300
G1 X68.348 Y24.177 Z-143.365 B-3.459 C-480.000 U6.764 F300
G1 X69.223 Y25.693 Z-143.365 B-3.459 C-480.000 U6.778 F300
G1 X70.098 Y27.208 Z-143.365 B-3.459 C-480.000 U6.792 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 17/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-480.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X70.098 Y27.208 Z-143.365 B-3.459 C-480.000 F1200
G1 X70.973 Y28.724 Z-143.365 B-3.459 C-480.000 U6.806 F300
G1 X71.848 Y30.239 Z-143.365 B-3.459 C-480.000 U6.820 F300
G1 X72.723 Y31.755 Z-143.365 B-3.459 C-480.000 U6.834 F300
G1 X73.598 Y33.270 Z-143.365 B-3.459 C-480.000 U6.848 F300
G1 X74.473 Y34.786 Z-143.365 B-3.459 C-480.000 U6.862 F300
G1 X75.348 Y36.302 Z-143.365 B-3.459 C-480.000 U6.876 F300
G1 X76.223 Y37.817 Z-143.365 B-3.459 C-480.000 U6.890 F300
G1 X77.098 Y39.333 Z-143.365 B-3.459 C-480.000 U6.904 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 18/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-600.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X75.694 Y48.354 Z-143.365 B-3.459 C-600.000 F1200
G1 X76.569 Y46.839 Z-143.365 B-3.459 C-600.000 U6.918 F300
G1 X77.444 Y45.323 Z-143.365 B-3.459 C-600.000 U6.932 F300
G1 X78.319 Y43.808 Z-143.365 B-3.459 C-600.000 U6.946 F300
G1 X79.194 Y42.292 Z-143.365 B-3.459 C-600.000 U6.960 F300
G1 X80.069 Y40.776 Z-143.365 B-3.459 C-600.000 U6.974 F300
G1 X80.944 Y39.261 Z-143.365 B-3.459 C-600.000 U6.988 F300
G1 X81.819 Y37.745 Z-143.365 B-3.459 C-600.000 U7.002 F300
G1 X82.694 Y36.230 Z-143.365 B-3.459 C-600.000 U7.016 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 19/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-660.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X87.902 Y37.040 Z-143.365 B-3.459 C-660.000 F1200
G1 X87.027 Y35.525 Z-143.365 B-3.459 C-660.000 U7.030 F300
G1 X86.152 Y34.009 Z-143.365 B-3.459 C-660.000 U7.044 F300
G1 X85.277 Y32.494 Z-143.365 B-3.459 C-660.000 U7.058 F300
G1 X84.402 Y30.978 Z-143.365 B-3.459 C-660.000 U7.072 F300
G1 X83.527 Y29.463 Z-143.365 B-3.459 C-660.000 U7.086 F300
G1 X82.652 Y27.947 Z-143.365 B-3.459 C-660.000 U7.100 F300
G1 X81.777 Y26.432 Z-143.365 B-3.459 C-660.000 U7.114 F300
G1 X80.902 Y24.916 Z-143.365 B-3.459 C-660.000 U7.128 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 20/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-540.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X73.791 Y19.189 Z-143.365 B-3.459 C-540.000 F1200
G1 X75.541 Y19.189 Z-143.365 B-3.459 C-540.000 U7.142 F300
G1 X77.291 Y19.189 Z-143.365 B-3.459 C-540.000 U7.156 F300
G1 X79.041 Y19.189 Z-143.365 B-3.459 C-540.000 U7.170 F300
G1 X80.791 Y19.189 Z-143.365 B-3.459 C-540.000 U7.184 F300
G1 X82.541 Y19.189 Z-143.365 B-3.459 C-540.000 U7.198 F300
G1 X84.291 Y19.189 Z-143.365 B-3.459 C-540.000 U7.212 F300
G1 X86.041 Y19.189 Z-143.365 B-3.459 C-540.000 U7.226 F300
G1 X87.791 Y19.189 Z-143.365 B-3.459 C-540.000 U7.240 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 21/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-420.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X96.306 Y15.895 Z-143.365 B-3.459 C-420.000 F1200
G1 X95.431 Y17.410 Z-143.365 B-3.459 C-420.000 U7.254 F300
G1 X94.556 Y18.926 Z-143.365 B-3.459 C-420.000 U7.268 F300
G1 X93.681 Y20.441 Z-143.365 B-3.459 C-420.000 U7.282 F300
G1 X92.806 Y21.957 Z-143.365 B-3.459 C-420.000 U7.296 F300
G1 X91.931 Y23.472 Z-143.365 B-3.459 C-420.000 U7.310 F300
G1 X91.056 Y24.988 Z-143.365 B-3.459 C-420.000 U7.324 F300
G1 X90.181 Y26.503 Z-143.365 B-3.459 C-420.000 U7.338 F300
G1 X89.306 Y28.019 Z-143.365 B-3.459 C-420.000 U7.352 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 22/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-360.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X91.209 Y32.935 Z-143.365 B-3.459 C-360.000 F1200
G1 X89.459 Y32.935 Z-143.365 B-3.459 C-360.000 U7.366 F300
G1 X87.709 Y32.935 Z-143.365 B-3.459 C-360.000 U7.380 F300
G1 X85.959 Y32.935 Z-143.365 B-3.459 C-360.000 U7.394 F300
G1 X84.209 Y32.935 Z-143.365 B-3.459 C-360.000 U7.408 F300
G1 X82.459 Y32.935 Z-143.365 B-3.459 C-360.000 U7.422 F300
G1 X80.709 Y32.935 Z-143.365 B-3.459 C-360.000 U7.436 F300
G1 X78.959 Y32.935 Z-143.365 B-3.459 C-360.000 U7.450 F300
G1 X77.209 Y32.935 Z-143.365 B-3.459 C-360.000 U7.464 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 23/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-240.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X68.694 Y36.230 Z-143.365 B-3.459 C-240.000 F1200
G1 X69.569 Y34.714 Z-143.365 B-3.459 C-240.000 U7.478 F300
G1 X70.444 Y33.199 Z-143.365 B-3.459 C-240.000 U7.492 F300
G1 X71.319 Y31.683 Z-143.365 B-3.459 C-240.000 U7.506 F300
G1 X72.194 Y30.168 Z-143.365 B-3.459 C-240.000 U7.520 F300
G1 X73.069 Y28.652 Z-143.365 B-3.459 C-240.000 U7.534 F300
G1 X73.944 Y27.137 Z-143.365 B-3.459 C-240.000 U7.548 F300
G1 X74.819 Y25.621 Z-143.365 B-3.459 C-240.000 U7.562 F300
G1 X75.694 Y24.105 Z-143.365 B-3.459 C-240.000 U7.576 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 24/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-360.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X84.209 Y20.811 Z-143.365 B-3.459 C-360.000 F1200
G1 X82.459 Y20.811 Z-143.365 B-3.459 C-360.000 U7.590 F300
G1 X80.709 Y20.811 Z-143.365 B-3.459 C-360.000 U7.604 F300
G1 X78.959 Y20.811 Z-143.365 B-3.459 C-360.000 U7.618 F300
G1 X77.209 Y20.811 Z-143.365 B-3.459 C-360.000 U7.632 F300
G1 X75.459 Y20.811 Z-143.365 B-3.459 C-360.000 U7.646 F300
G1 X73.709 Y20.811 Z-143.365 B-3.459 C-360.000 U7.660 F300
G1 X71.959 Y20.811 Z-143.365 B-3.459 C-360.000 U7.674 F300
G1 X70.209 Y20.811 Z-143.365 B-3.459 C-360.000 U7.688 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U2.688 F240
; --- edge 25/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-510.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X61.353 Y23.336 Z-133.085 B-2.094 C-510.000 F1200
; pressure preload before print pass
G1 U7.688 F120
G4 P200
G1 X62.228 Y23.841 Z-131.657 B-2.094 C-510.000 U7.702 F300
G1 X63.103 Y24.346 Z-130.228 B-2.094 C-510.000 U7.716 F300
G1 X63.978 Y24.851 Z-128.799 B-2.094 C-510.000 U7.730 F300
G1 X64.853 Y25.356 Z-127.370 B-2.094 C-510.000 U7.744 F300
G1 X65.728 Y25.862 Z-125.941 B-2.094 C-510.000 U7.758 F300
G1 X66.603 Y26.367 Z-124.512 B-2.094 C-510.000 U7.772 F300
G1 X67.478 Y26.872 Z-123.083 B-2.094 C-510.000 U7.786 F300
G1 X68.353 Y27.377 Z-121.654 B-2.094 C-510.000 U7.800 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U2.800 F240
; --- edge 26/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-390.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X98.935 Y27.298 Z-133.085 B-2.094 C-390.000 F1200
; pressure preload before print pass
G1 U7.800 F120
G4 P200
G1 X98.060 Y27.803 Z-131.657 B-2.094 C-390.000 U7.814 F300
G1 X97.185 Y28.308 Z-130.228 B-2.094 C-390.000 U7.828 F300
G1 X96.310 Y28.813 Z-128.799 B-2.094 C-390.000 U7.842 F300
G1 X95.435 Y29.319 Z-127.370 B-2.094 C-390.000 U7.856 F300
G1 X94.560 Y29.824 Z-125.941 B-2.094 C-390.000 U7.870 F300
G1 X93.685 Y30.329 Z-124.512 B-2.094 C-390.000 U7.884 F300
G1 X92.810 Y30.834 Z-123.083 B-2.094 C-390.000 U7.898 F300
G1 X91.935 Y31.339 Z-121.654 B-2.094 C-390.000 U7.912 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U2.912 F240
; --- edge 27/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-510.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X68.353 Y11.211 Z-133.085 B-2.094 C-510.000 F1200
; pressure preload before print pass
G1 U7.912 F120
G4 P200
G1 X69.228 Y11.717 Z-131.657 B-2.094 C-510.000 U7.926 F300
G1 X70.103 Y12.222 Z-130.228 B-2.094 C-510.000 U7.940 F300
G1 X70.978 Y12.727 Z-128.799 B-2.094 C-510.000 U7.954 F300
G1 X71.853 Y13.232 Z-127.370 B-2.094 C-510.000 U7.968 F300
G1 X72.728 Y13.737 Z-125.941 B-2.094 C-510.000 U7.982 F300
G1 X73.603 Y14.242 Z-124.512 B-2.094 C-510.000 U7.996 F300
G1 X74.478 Y14.748 Z-123.083 B-2.094 C-510.000 U8.010 F300
G1 X75.353 Y15.253 Z-121.654 B-2.094 C-510.000 U8.024 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U3.024 F240
; --- edge 28/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-390.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X91.935 Y15.174 Z-133.085 B-2.094 C-390.000 F1200
; pressure preload before print pass
G1 U8.024 F120
G4 P200
G1 X91.060 Y15.679 Z-131.657 B-2.094 C-390.000 U8.038 F300
G1 X90.185 Y16.184 Z-130.228 B-2.094 C-390.000 U8.052 F300
G1 X89.310 Y16.689 Z-128.799 B-2.094 C-390.000 U8.066 F300
G1 X88.435 Y17.194 Z-127.370 B-2.094 C-390.000 U8.080 F300
G1 X87.560 Y17.699 Z-125.941 B-2.094 C-390.000 U8.094 F300
G1 X86.685 Y18.205 Z-124.512 B-2.094 C-390.000 U8.108 F300
G1 X85.810 Y18.710 Z-123.083 B-2.094 C-390.000 U8.122 F300
G1 X84.935 Y19.215 Z-121.654 B-2.094 C-390.000 U8.136 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U3.136 F240
; --- edge 29/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-270.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X69.712 Y45.740 Z-133.085 B-2.094 C-270.000 F1200
; pressure preload before print pass
G1 U8.136 F120
G4 P200
G1 X69.712 Y44.729 Z-131.657 B-2.094 C-270.000 U8.150 F300
G1 X69.712 Y43.719 Z-130.228 B-2.094 C-270.000 U8.164 F300
G1 X69.712 Y42.708 Z-128.799 B-2.094 C-270.000 U8.178 F300
G1 X69.712 Y41.698 Z-127.370 B-2.094 C-270.000 U8.192 F300
G1 X69.712 Y40.688 Z-125.941 B-2.094 C-270.000 U8.206 F300
G1 X69.712 Y39.677 Z-124.512 B-2.094 C-270.000 U8.220 F300
G1 X69.712 Y38.667 Z-123.083 B-2.094 C-270.000 U8.234 F300
G1 X69.712 Y37.657 Z-121.654 B-2.094 C-270.000 U8.248 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U3.248 F240
; --- edge 30/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-270.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X83.712 Y45.740 Z-133.085 B-2.094 C-270.000 F1200
; pressure preload before print pass
G1 U8.248 F120
G4 P200
G1 X83.712 Y44.729 Z-131.657 B-2.094 C-270.000 U8.262 F300
G1 X83.712 Y43.719 Z-130.228 B-2.094 C-270.000 U8.276 F300
G1 X83.712 Y42.708 Z-128.799 B-2.094 C-270.000 U8.290 F300
G1 X83.712 Y41.698 Z-127.370 B-2.094 C-270.000 U8.304 F300
G1 X83.712 Y40.688 Z-125.941 B-2.094 C-270.000 U8.318 F300
G1 X83.712 Y39.677 Z-124.512 B-2.094 C-270.000 U8.332 F300
G1 X83.712 Y38.667 Z-123.083 B-2.094 C-270.000 U8.346 F300
G1 X83.712 Y37.657 Z-121.654 B-2.094 C-270.000 U8.360 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U3.360 F240
; --- edge 31/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-270.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X76.712 Y57.864 Z-133.085 B-2.094 C-270.000 F1200
; pressure preload before print pass
G1 U8.360 F120
G4 P200
G1 X76.712 Y56.854 Z-131.657 B-2.094 C-270.000 U8.374 F300
G1 X76.712 Y55.843 Z-130.228 B-2.094 C-270.000 U8.388 F300
G1 X76.712 Y54.833 Z-128.799 B-2.094 C-270.000 U8.402 F300
G1 X76.712 Y53.822 Z-127.370 B-2.094 C-270.000 U8.416 F300
G1 X76.712 Y52.812 Z-125.941 B-2.094 C-270.000 U8.430 F300
G1 X76.712 Y51.802 Z-124.512 B-2.094 C-270.000 U8.444 F300
G1 X76.712 Y50.791 Z-123.083 B-2.094 C-270.000 U8.458 F300
G1 X76.712 Y49.781 Z-121.654 B-2.094 C-270.000 U8.472 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U3.472 F240
; --- edge 32/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-390.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X105.935 Y15.174 Z-133.085 B-2.094 C-390.000 F1200
; pressure preload before print pass
G1 U8.472 F120
G4 P200
G1 X105.060 Y15.679 Z-131.657 B-2.094 C-390.000 U8.486 F300
G1 X104.185 Y16.184 Z-130.228 B-2.094 C-390.000 U8.500 F300
G1 X103.310 Y16.689 Z-128.799 B-2.094 C-390.000 U8.514 F300
G1 X102.435 Y17.194 Z-127.370 B-2.094 C-390.000 U8.528 F300
G1 X101.560 Y17.699 Z-125.941 B-2.094 C-390.000 U8.542 F300
G1 X100.685 Y18.205 Z-124.512 B-2.094 C-390.000 U8.556 F300
G1 X99.810 Y18.710 Z-123.083 B-2.094 C-390.000 U8.570 F300
G1 X98.935 Y19.215 Z-121.654 B-2.094 C-390.000 U8.584 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U3.584 F240
; --- edge 33/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-510.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X54.353 Y11.211 Z-133.085 B-2.094 C-510.000 F1200
; pressure preload before print pass
G1 U8.584 F120
G4 P200
G1 X55.228 Y11.717 Z-131.657 B-2.094 C-510.000 U8.598 F300
G1 X56.103 Y12.222 Z-130.228 B-2.094 C-510.000 U8.612 F300
G1 X56.978 Y12.727 Z-128.799 B-2.094 C-510.000 U8.626 F300
G1 X57.853 Y13.232 Z-127.370 B-2.094 C-510.000 U8.640 F300
G1 X58.728 Y13.737 Z-125.941 B-2.094 C-510.000 U8.654 F300
G1 X59.603 Y14.242 Z-124.512 B-2.094 C-510.000 U8.668 F300
G1 X60.478 Y14.748 Z-123.083 B-2.094 C-510.000 U8.682 F300
G1 X61.353 Y15.253 Z-121.654 B-2.094 C-510.000 U8.696 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U3.696 F240
; --- edge 34/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-480.000, head_lead=-5.209 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X70.098 Y19.125 Z-131.934 B-3.459 C-480.000 F1200
; pressure preload before print pass
G1 U8.696 F120
G4 P200
G1 X70.973 Y20.641 Z-131.934 B-3.459 C-480.000 U8.710 F300
G1 X71.848 Y22.156 Z-131.934 B-3.459 C-480.000 U8.724 F300
G1 X72.723 Y23.672 Z-131.934 B-3.459 C-480.000 U8.738 F300
G1 X73.598 Y25.188 Z-131.934 B-3.459 C-480.000 U8.752 F300
G1 X74.473 Y26.703 Z-131.934 B-3.459 C-480.000 U8.766 F300
G1 X75.348 Y28.219 Z-131.934 B-3.459 C-480.000 U8.780 F300
G1 X76.223 Y29.734 Z-131.934 B-3.459 C-480.000 U8.794 F300
G1 X77.098 Y31.250 Z-131.934 B-3.459 C-480.000 U8.808 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 35/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-600.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X75.694 Y40.271 Z-131.934 B-3.459 C-600.000 F1200
G1 X76.569 Y38.756 Z-131.934 B-3.459 C-600.000 U8.822 F300
G1 X77.444 Y37.240 Z-131.934 B-3.459 C-600.000 U8.836 F300
G1 X78.319 Y35.725 Z-131.934 B-3.459 C-600.000 U8.850 F300
G1 X79.194 Y34.209 Z-131.934 B-3.459 C-600.000 U8.864 F300
G1 X80.069 Y32.694 Z-131.934 B-3.459 C-600.000 U8.878 F300
G1 X80.944 Y31.178 Z-131.934 B-3.459 C-600.000 U8.892 F300
G1 X81.819 Y29.662 Z-131.934 B-3.459 C-600.000 U8.906 F300
G1 X82.694 Y28.147 Z-131.934 B-3.459 C-600.000 U8.920 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; keep pressure charged for continuous horizontal tip-pivot into next edge
; --- edge 36/39 ---
; len=14.000 mm, angle_error=0.094 deg, B=-3.459, C=-720.000, head_lead=-5.209 mm, head_front_ok=0
; continuous horizontal transition: tip-fixed pivot to next line direction
; (same tip vertex, new B/C and corresponding stage XYZ)
G1 X91.209 Y24.852 Z-131.934 B-3.459 C-720.000 F1200
G1 X89.459 Y24.852 Z-131.934 B-3.459 C-720.000 U8.934 F300
G1 X87.709 Y24.852 Z-131.934 B-3.459 C-720.000 U8.948 F300
G1 X85.959 Y24.852 Z-131.934 B-3.459 C-720.000 U8.962 F300
G1 X84.209 Y24.852 Z-131.934 B-3.459 C-720.000 U8.976 F300
G1 X82.459 Y24.852 Z-131.934 B-3.459 C-720.000 U8.990 F300
G1 X80.709 Y24.852 Z-131.934 B-3.459 C-720.000 U9.004 F300
G1 X78.959 Y24.852 Z-131.934 B-3.459 C-720.000 U9.018 F300
G1 X77.209 Y24.852 Z-131.934 B-3.459 C-720.000 U9.032 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U4.032 F240
; --- edge 37/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-630.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X76.712 Y49.781 Z-121.654 B-2.094 C-630.000 F1200
; pressure preload before print pass
G1 U9.032 F120
G4 P200
G1 X76.712 Y48.771 Z-120.226 B-2.094 C-630.000 U9.046 F300
G1 X76.712 Y47.760 Z-118.797 B-2.094 C-630.000 U9.060 F300
G1 X76.712 Y46.750 Z-117.368 B-2.094 C-630.000 U9.074 F300
G1 X76.712 Y45.740 Z-115.939 B-2.094 C-630.000 U9.088 F300
G1 X76.712 Y44.729 Z-114.510 B-2.094 C-630.000 U9.102 F300
G1 X76.712 Y43.719 Z-113.081 B-2.094 C-630.000 U9.116 F300
G1 X76.712 Y42.708 Z-111.652 B-2.094 C-630.000 U9.130 F300
G1 X76.712 Y41.698 Z-110.223 B-2.094 C-630.000 U9.144 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U4.144 F240
; --- edge 38/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-750.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X98.935 Y19.215 Z-121.654 B-2.094 C-750.000 F1200
; pressure preload before print pass
G1 U9.144 F120
G4 P200
G1 X98.060 Y19.720 Z-120.226 B-2.094 C-750.000 U9.158 F300
G1 X97.185 Y20.225 Z-118.797 B-2.094 C-750.000 U9.172 F300
G1 X96.310 Y20.731 Z-117.368 B-2.094 C-750.000 U9.186 F300
G1 X95.435 Y21.236 Z-115.939 B-2.094 C-750.000 U9.200 F300
G1 X94.560 Y21.741 Z-114.510 B-2.094 C-750.000 U9.214 F300
G1 X93.685 Y22.246 Z-113.081 B-2.094 C-750.000 U9.228 F300
G1 X92.810 Y22.751 Z-111.652 B-2.094 C-750.000 U9.242 F300
G1 X91.935 Y23.256 Z-110.223 B-2.094 C-750.000 U9.256 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U4.256 F240
; --- edge 39/39 ---
; len=14.000 mm, angle_error=0.068 deg, B=-2.094, C=-870.000, head_lead=-10.380 mm, head_front_ok=0
; non-print travel to next strut start (tip exact)
G1 X61.353 Y15.253 Z-121.654 B-2.094 C-870.000 F1200
; pressure preload before print pass
G1 U9.256 F120
G4 P200
G1 X62.228 Y15.758 Z-120.226 B-2.094 C-870.000 U9.270 F300
G1 X63.103 Y16.263 Z-118.797 B-2.094 C-870.000 U9.284 F300
G1 X63.978 Y16.768 Z-117.368 B-2.094 C-870.000 U9.298 F300
G1 X64.853 Y17.274 Z-115.939 B-2.094 C-870.000 U9.312 F300
G1 X65.728 Y17.779 Z-114.510 B-2.094 C-870.000 U9.326 F300
G1 X66.603 Y18.284 Z-113.081 B-2.094 C-870.000 U9.340 F300
G1 X67.478 Y18.789 Z-111.652 B-2.094 C-870.000 U9.354 F300
G1 X68.353 Y19.294 Z-110.223 B-2.094 C-870.000 U9.368 F300
; end-of-pass dwell for node formation / liquid flow
G4 P200
; pressure release before travel
G1 U4.368 F240
; safe end move: raise to safe Z, move XY, then dive to end Z
G1 Z0.000 B0.000 C0.000 F1200
G1 X65.000 Y20.000 B0.000 C0.000 F1200
G1 Z0.000 B0.000 C0.000 F1200
; emitted edges = 39
; bbox warning count = 0
; --- end ---
